/**
 * Template Seed — 100 premium resume templates
 * 15 distinct layout types × 16 colour palettes across 6 professional categories
 *
 * Layout types used:
 *   single-standard  → BaseLayout          (clean, ATS-safe single column)
 *   professional     → ProfessionalLayout  (accent-bar header, 3-col skills box)
 *   executive        → ExecutiveLayout     (serif, formal, 2-col skills grid)
 *   classic          → ClassicLayout       (Georgia serif, centred, underline sections)
 *   contemporary     → ContemporaryLayout  (full-width colour band header)
 *   two-sidebar      → TwoColumnSidebarLayout (32/68 tinted sidebar / main, skill pills)
 *   compact          → CompactLayout       (dense 70/30, one-page)
 *   minimal          → ModernMinimalLayout (centred, whitespace-rich)
 *   tech             → TechLayout          (terminal-style monospace header)
 *   bold-modern      → BoldModernLayout    (900-weight, filled section bars)
 *   timeline         → TimelineLayout      (vertical timeline spine)
 *   academic         → AcademicLayout      (centred serif, publication-ready)
 *   portfolio        → PortfolioLayout     (photo + project grid)
 *   creative         → CreativeLayout      (full-height colour sidebar, white text)
 *   infographic      → InfographicLayout   (sidebar skill bars, metric cards)
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const templateSeeds = [

  // ══════════════════════════════════════════════════════════════════
  // ATS-PROFESSIONAL  (25 templates)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'meridian',
    name: 'Meridian',
    description: 'Refined single-column layout built for top-tier ATS systems. Navy accent with crisp section dividers.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['finance', 'consulting', 'corporate', 'banking'],
    targetRoles: ['business-analyst', 'financial-analyst', 'consultant', 'manager'],
    experienceLevel: 'mid', searchKeywords: ['meridian', 'corporate', 'ats', 'navy', 'professional'],
    popularityScore: 97, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: true, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'navy' },
  },
  {
    id: 'sterling',
    name: 'Sterling',
    description: 'Polished professional with a bold left-accent header bar and compact 3-column skills grid.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['finance', 'accounting', 'investment', 'banking'],
    targetRoles: ['financial-analyst', 'accountant', 'auditor', 'investment-banker'],
    experienceLevel: 'senior', searchKeywords: ['sterling', 'finance', 'accounting', 'charcoal'],
    popularityScore: 90, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'charcoal' },
  },
  {
    id: 'harbor',
    name: 'Harbor',
    description: 'Calm, clinical single-column layout with teal tones ideal for healthcare and wellness professionals.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['healthcare', 'medical', 'clinical', 'nursing'],
    targetRoles: ['nurse', 'physician', 'healthcare-manager', 'clinical-specialist'],
    experienceLevel: 'mid', searchKeywords: ['harbor', 'healthcare', 'medical', 'teal', 'clinical'],
    popularityScore: 83, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'teal' },
  },
  {
    id: 'counsel',
    name: 'Counsel',
    description: 'Traditional serif layout for legal professionals. Centred header, understated elegance.',
    primaryCategory: 'ats-professional', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['legal', 'law', 'compliance', 'paralegal'],
    targetRoles: ['attorney', 'paralegal', 'legal-counsel', 'compliance-officer'],
    experienceLevel: 'senior', searchKeywords: ['counsel', 'legal', 'law', 'attorney', 'classic'],
    popularityScore: 79, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'slate' },
  },
  {
    id: 'atlas',
    name: 'Atlas',
    description: 'Structured professional with accent-bar header designed for operations and supply chain leaders.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['operations', 'logistics', 'manufacturing', 'supply-chain'],
    targetRoles: ['operations-manager', 'logistics-coordinator', 'supply-chain-analyst'],
    experienceLevel: 'mid', searchKeywords: ['atlas', 'operations', 'logistics', 'supply chain'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'slate' },
  },
  {
    id: 'summit',
    name: 'Summit',
    description: 'Contemporary full-width band header in forest green. Stands out while remaining fully ATS-friendly.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['consulting', 'strategy', 'management', 'advisory'],
    targetRoles: ['management-consultant', 'strategy-analyst', 'advisor'],
    experienceLevel: 'senior', searchKeywords: ['summit', 'consulting', 'strategy', 'contemporary', 'forest'],
    popularityScore: 86, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'forest' },
  },
  {
    id: 'quota',
    name: 'Quota',
    description: 'Results-forward contemporary layout. Vibrant royal-blue band header for high-performing sales professionals.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['sales', 'business-development', 'account-management'],
    targetRoles: ['sales-manager', 'account-executive', 'business-development', 'sales-director'],
    experienceLevel: 'mid', searchKeywords: ['quota', 'sales', 'revenue', 'business development'],
    popularityScore: 81, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'royal' },
  },
  {
    id: 'broadcast',
    name: 'Broadcast',
    description: 'Dynamic professional layout with a rich wine accent. Built for marketing, PR and communications roles.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['marketing', 'pr', 'communications', 'media'],
    targetRoles: ['marketing-manager', 'pr-specialist', 'communications-director', 'brand-manager'],
    experienceLevel: 'mid', searchKeywords: ['broadcast', 'marketing', 'pr', 'communications', 'media'],
    popularityScore: 78, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'wine' },
  },
  {
    id: 'pinnacle',
    name: 'Pinnacle',
    description: 'Authoritative burgundy single-column design for HR and people-operations leaders.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['human-resources', 'people-ops', 'talent', 'recruiting'],
    targetRoles: ['hr-manager', 'recruiter', 'talent-acquisition', 'people-operations'],
    experienceLevel: 'senior', searchKeywords: ['pinnacle', 'hr', 'people', 'talent', 'recruiting'],
    popularityScore: 74, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'burgundy' },
  },
  {
    id: 'charter',
    name: 'Charter',
    description: 'Classic serif layout with a navy palette. Ideal for government, nonprofit and public-sector professionals.',
    primaryCategory: 'ats-professional', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['government', 'nonprofit', 'public-sector', 'policy'],
    targetRoles: ['policy-analyst', 'program-manager', 'grant-writer', 'public-administrator'],
    experienceLevel: 'mid', searchKeywords: ['charter', 'government', 'nonprofit', 'public', 'policy'],
    popularityScore: 71, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'navy' },
  },
  {
    id: 'stratum',
    name: 'Stratum',
    description: 'Two-column sidebar with graphite tones. Professional portrait-style layout for business development leaders.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['business-development', 'sales', 'partnerships', 'corporate'],
    targetRoles: ['business-development-manager', 'partnerships-director', 'account-manager'],
    experienceLevel: 'senior', searchKeywords: ['stratum', 'business development', 'sidebar', 'graphite'],
    popularityScore: 84, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'graphite' },
  },
  {
    id: 'forte',
    name: 'Forte',
    description: 'Dense compact layout that fits a decade of experience on a single page. Charcoal precision.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['finance', 'consulting', 'corporate', 'management'],
    targetRoles: ['senior-manager', 'director', 'principal', 'managing-director'],
    experienceLevel: 'senior', searchKeywords: ['forte', 'compact', 'one-page', 'senior', 'dense'],
    popularityScore: 82, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'compact', colorPalette: 'charcoal' },
  },
  {
    id: 'ledger',
    name: 'Ledger',
    description: 'Precise single-column layout in teal for accounting, audit and tax professionals.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['accounting', 'audit', 'tax', 'finance'],
    targetRoles: ['accountant', 'auditor', 'tax-specialist', 'cpa', 'controller'],
    experienceLevel: 'mid', searchKeywords: ['ledger', 'accounting', 'audit', 'tax', 'cpa'],
    popularityScore: 75, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'teal' },
  },
  {
    id: 'nexus',
    name: 'Nexus',
    description: 'Contemporary indigo band header that signals modern cross-functional project management skills.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['project-management', 'product', 'operations', 'technology'],
    targetRoles: ['project-manager', 'program-manager', 'product-owner', 'scrum-master'],
    experienceLevel: 'mid', searchKeywords: ['nexus', 'project management', 'program', 'indigo', 'pmp'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'indigo' },
  },
  {
    id: 'paladin',
    name: 'Paladin',
    description: 'Dependable professional layout in navy. Trusted by risk, compliance and insurance professionals worldwide.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['insurance', 'risk-management', 'compliance', 'banking'],
    targetRoles: ['risk-analyst', 'compliance-officer', 'insurance-underwriter', 'actuary'],
    experienceLevel: 'mid', searchKeywords: ['paladin', 'risk', 'compliance', 'insurance', 'navy'],
    popularityScore: 72, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'navy' },
  },
  {
    id: 'caliber',
    name: 'Caliber',
    description: 'Measured and precise single-column design in slate. The benchmark template for management professionals.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['management', 'corporate', 'strategy', 'operations'],
    targetRoles: ['general-manager', 'operations-director', 'chief-of-staff', 'vp'],
    experienceLevel: 'senior', searchKeywords: ['caliber', 'management', 'director', 'slate', 'precise'],
    popularityScore: 77, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'slate' },
  },
  {
    id: 'landmark',
    name: 'Landmark',
    description: 'Two-column sidebar in navy for real estate, property and built-environment professionals.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['real-estate', 'property', 'construction', 'architecture'],
    targetRoles: ['real-estate-agent', 'property-manager', 'development-director', 'broker'],
    experienceLevel: 'mid', searchKeywords: ['landmark', 'real estate', 'property', 'sidebar', 'navy'],
    popularityScore: 70, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'navy' },
  },
  {
    id: 'catalyst',
    name: 'Catalyst',
    description: 'Ocean-blue contemporary header that signals innovation. Loved by consultants and strategists.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['consulting', 'innovation', 'strategy', 'advisory'],
    targetRoles: ['strategy-consultant', 'innovation-manager', 'business-analyst', 'advisor'],
    experienceLevel: 'mid', searchKeywords: ['catalyst', 'consulting', 'innovation', 'ocean', 'contemporary'],
    popularityScore: 83, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'ocean' },
  },
  {
    id: 'ember',
    name: 'Ember',
    description: 'Warm rust-toned professional layout for hospitality, food & beverage and tourism professionals.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['hospitality', 'food-beverage', 'tourism', 'retail'],
    targetRoles: ['hotel-manager', 'restaurant-manager', 'event-coordinator', 'operations-manager'],
    experienceLevel: 'mid', searchKeywords: ['ember', 'hospitality', 'food', 'tourism', 'rust'],
    popularityScore: 68, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'rust' },
  },
  {
    id: 'prism',
    name: 'Prism',
    description: 'Violet contemporary band header with pill-style skills. Built for marketing analytics and growth roles.',
    primaryCategory: 'ats-professional', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['marketing', 'analytics', 'growth', 'digital'],
    targetRoles: ['marketing-analyst', 'growth-hacker', 'digital-marketer', 'seo-specialist'],
    experienceLevel: 'mid', searchKeywords: ['prism', 'marketing', 'analytics', 'growth', 'violet'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'violet' },
  },
  {
    id: 'vanguard',
    name: 'Vanguard',
    description: 'Graphite single-column for defence, military and security professionals seeking civilian roles.',
    primaryCategory: 'ats-professional', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['defence', 'security', 'government', 'law-enforcement'],
    targetRoles: ['security-manager', 'defence-analyst', 'intelligence-officer', 'operations-manager'],
    experienceLevel: 'senior', searchKeywords: ['vanguard', 'defence', 'military', 'security', 'graphite'],
    popularityScore: 71, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'graphite' },
  },
  {
    id: 'sovereign',
    name: 'Sovereign',
    description: 'Stately classic serif layout in charcoal for senior finance executives and board members.',
    primaryCategory: 'ats-professional', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['finance', 'banking', 'investment', 'private-equity'],
    targetRoles: ['cfo', 'finance-director', 'investment-director', 'treasurer'],
    experienceLevel: 'executive', searchKeywords: ['sovereign', 'finance', 'executive', 'charcoal', 'classic'],
    popularityScore: 79, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'charcoal' },
  },
  {
    id: 'signal',
    name: 'Signal',
    description: 'Compact teal layout engineered for communications, media and PR professionals who need one page.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['communications', 'media', 'pr', 'journalism'],
    targetRoles: ['communications-manager', 'journalist', 'editor', 'content-strategist'],
    experienceLevel: 'mid', searchKeywords: ['signal', 'communications', 'media', 'pr', 'compact'],
    popularityScore: 73, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'compact', colorPalette: 'teal' },
  },
  {
    id: 'dominion',
    name: 'Dominion',
    description: 'Executive-class slate design with formal serif typography for C-suite and senior leadership.',
    primaryCategory: 'ats-professional', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['executive', 'corporate', 'leadership', 'board'],
    targetRoles: ['ceo', 'president', 'managing-director', 'executive-director'],
    experienceLevel: 'executive', searchKeywords: ['dominion', 'executive', 'leadership', 'slate', 'formal'],
    popularityScore: 85, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'slate' },
  },
  {
    id: 'paragon',
    name: 'Paragon',
    description: 'The gold-standard professional layout. Navy accent-bar header, tinted skills box. Suits any industry.',
    primaryCategory: 'ats-professional', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['corporate', 'management', 'finance', 'consulting'],
    targetRoles: ['manager', 'director', 'analyst', 'specialist'],
    experienceLevel: 'mid', searchKeywords: ['paragon', 'professional', 'navy', 'versatile', 'corporate'],
    popularityScore: 91, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'navy' },
  },

  // ══════════════════════════════════════════════════════════════════
  // TECH-STARTUP  (20 templates)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'silicon',
    name: 'Silicon',
    description: 'Terminal-style indigo header with `$ whoami` prompt. The definitive layout for software engineers.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'software', 'engineering', 'startup'],
    targetRoles: ['software-engineer', 'full-stack-developer', 'backend-developer', 'swe'],
    experienceLevel: 'mid', searchKeywords: ['silicon', 'developer', 'software', 'engineer', 'tech', 'code'],
    popularityScore: 94, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'indigo' },
  },
  {
    id: 'kernel',
    name: 'Kernel',
    description: 'Monospace charcoal layout for systems, embedded and infrastructure engineers. No-nonsense and sharp.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'systems', 'infrastructure', 'embedded'],
    targetRoles: ['systems-engineer', 'embedded-developer', 'platform-engineer', 'c-developer'],
    experienceLevel: 'senior', searchKeywords: ['kernel', 'systems', 'embedded', 'infrastructure', 'charcoal'],
    popularityScore: 82, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'charcoal' },
  },
  {
    id: 'launchpad',
    name: 'Launchpad',
    description: 'High-impact bold-modern layout in royal blue. Built for startup founders and entrepreneurial roles.',
    primaryCategory: 'tech-startup', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['startup', 'entrepreneurship', 'product', 'technology'],
    targetRoles: ['founder', 'cto', 'product-manager', 'startup-executive'],
    experienceLevel: 'senior', searchKeywords: ['launchpad', 'startup', 'founder', 'bold', 'royal'],
    popularityScore: 88, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'royal' },
  },
  {
    id: 'circuit',
    name: 'Circuit',
    description: 'Tech terminal in teal for hardware, firmware and electrical engineering professionals.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['hardware', 'electrical', 'firmware', 'iot'],
    targetRoles: ['hardware-engineer', 'firmware-developer', 'electrical-engineer', 'iot-engineer'],
    experienceLevel: 'mid', searchKeywords: ['circuit', 'hardware', 'firmware', 'electrical', 'teal'],
    popularityScore: 77, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'teal' },
  },
  {
    id: 'axiom',
    name: 'Axiom',
    description: 'Clean minimal layout in slate for senior engineers who let their work speak for itself.',
    primaryCategory: 'tech-startup', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'software', 'engineering'],
    targetRoles: ['staff-engineer', 'principal-engineer', 'senior-developer', 'architect'],
    experienceLevel: 'senior', searchKeywords: ['axiom', 'minimal', 'senior', 'slate', 'clean'],
    popularityScore: 85, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'slate' },
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Bold-modern violet layout with filled section bars. Energetic and creative for frontend developers.',
    primaryCategory: 'tech-startup', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'frontend', 'web', 'startup'],
    targetRoles: ['frontend-developer', 'ui-developer', 'react-developer', 'web-developer'],
    experienceLevel: 'mid', searchKeywords: ['neon', 'frontend', 'web', 'violet', 'bold'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'violet' },
  },
  {
    id: 'stack',
    name: 'Stack',
    description: 'Ocean terminal layout for DevOps, cloud and platform engineers showcasing their tech stack.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['devops', 'cloud', 'infrastructure', 'sre'],
    targetRoles: ['devops-engineer', 'cloud-architect', 'sre', 'platform-engineer'],
    experienceLevel: 'mid', searchKeywords: ['stack', 'devops', 'cloud', 'aws', 'ocean', 'infrastructure'],
    popularityScore: 83, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'ocean' },
  },
  {
    id: 'vertex',
    name: 'Vertex',
    description: 'Indigo two-column sidebar giving architects and tech leads the space to showcase breadth and depth.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'architecture', 'engineering', 'leadership'],
    targetRoles: ['software-architect', 'tech-lead', 'principal-engineer', 'vp-engineering'],
    experienceLevel: 'senior', searchKeywords: ['vertex', 'architect', 'tech lead', 'indigo', 'sidebar'],
    popularityScore: 81, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'indigo' },
  },
  {
    id: 'deploy',
    name: 'Deploy',
    description: 'Graphite minimal layout for product engineers who ship fast and value clarity over decoration.',
    primaryCategory: 'tech-startup', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'product', 'engineering', 'startup'],
    targetRoles: ['product-engineer', 'full-stack-developer', 'engineering-manager', 'tech-pm'],
    experienceLevel: 'mid', searchKeywords: ['deploy', 'product', 'engineer', 'minimal', 'graphite'],
    popularityScore: 78, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'graphite' },
  },
  {
    id: 'cipher',
    name: 'Cipher',
    description: 'Navy terminal layout projecting trust and precision. The go-to for cybersecurity professionals.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['cybersecurity', 'security', 'technology', 'defence'],
    targetRoles: ['security-engineer', 'penetration-tester', 'soc-analyst', 'security-architect'],
    experienceLevel: 'mid', searchKeywords: ['cipher', 'security', 'cybersecurity', 'navy', 'tech'],
    popularityScore: 82, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'navy' },
  },
  {
    id: 'refactor',
    name: 'Refactor',
    description: 'Bold emerald layout for senior backend engineers and tech leads driving major code transformations.',
    primaryCategory: 'tech-startup', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'backend', 'engineering', 'leadership'],
    targetRoles: ['backend-developer', 'tech-lead', 'engineering-manager', 'staff-engineer'],
    experienceLevel: 'senior', searchKeywords: ['refactor', 'backend', 'tech lead', 'emerald', 'bold'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'emerald' },
  },
  {
    id: 'neural',
    name: 'Neural',
    description: 'Infographic-style with skill progress bars and visual sidebar. Purpose-built for AI and ML engineers.',
    primaryCategory: 'tech-startup', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['ai', 'machine-learning', 'data-science', 'research'],
    targetRoles: ['ml-engineer', 'ai-researcher', 'data-scientist', 'deep-learning-engineer'],
    experienceLevel: 'mid', searchKeywords: ['neural', 'ai', 'machine learning', 'data science', 'violet'],
    popularityScore: 87, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'infographic', colorPalette: 'violet' },
  },
  {
    id: 'interface',
    name: 'Interface',
    description: 'Portfolio-style with project cards and photo slot. Best for UX engineers blending design and code.',
    primaryCategory: 'tech-startup', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['ux', 'product-design', 'technology', 'startup'],
    targetRoles: ['ux-engineer', 'ui-developer', 'product-designer', 'design-engineer'],
    experienceLevel: 'mid', searchKeywords: ['interface', 'ux', 'portfolio', 'design engineer', 'royal'],
    popularityScore: 79, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'portfolio', colorPalette: 'royal' },
  },
  {
    id: 'daemon',
    name: 'Daemon',
    description: 'Dark charcoal terminal for infrastructure and reliability engineers who live in the command line.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['infrastructure', 'sre', 'devops', 'systems'],
    targetRoles: ['infrastructure-engineer', 'sre', 'systems-administrator', 'database-engineer'],
    experienceLevel: 'senior', searchKeywords: ['daemon', 'infrastructure', 'sre', 'charcoal', 'terminal'],
    popularityScore: 74, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'charcoal' },
  },
  {
    id: 'horizon',
    name: 'Horizon',
    description: 'Teal minimal layout with generous whitespace for data engineers and analytics professionals.',
    primaryCategory: 'tech-startup', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['data', 'analytics', 'engineering', 'technology'],
    targetRoles: ['data-engineer', 'analytics-engineer', 'bi-developer', 'data-platform-engineer'],
    experienceLevel: 'mid', searchKeywords: ['horizon', 'data', 'analytics', 'teal', 'minimal'],
    popularityScore: 77, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'teal' },
  },
  {
    id: 'sprint',
    name: 'Sprint',
    description: 'Bold ocean layout with filled section bars for agile product managers and scrum practitioners.',
    primaryCategory: 'tech-startup', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['product', 'agile', 'startup', 'technology'],
    targetRoles: ['product-manager', 'scrum-master', 'agile-coach', 'product-owner'],
    experienceLevel: 'mid', searchKeywords: ['sprint', 'product', 'agile', 'ocean', 'bold', 'pm'],
    popularityScore: 81, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'ocean' },
  },
  {
    id: 'flux',
    name: 'Flux',
    description: 'Two-column graphite sidebar designed for cloud architects and multi-discipline tech leaders.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['cloud', 'architecture', 'technology', 'startup'],
    targetRoles: ['cloud-architect', 'solutions-architect', 'enterprise-architect', 'cto'],
    experienceLevel: 'senior', searchKeywords: ['flux', 'cloud', 'architect', 'graphite', 'sidebar'],
    popularityScore: 79, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'graphite' },
  },
  {
    id: 'matrix',
    name: 'Matrix',
    description: 'Infographic slate layout with visual skill bars. Designed for data scientists and ML specialists.',
    primaryCategory: 'tech-startup', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['data-science', 'ai', 'analytics', 'research'],
    targetRoles: ['data-scientist', 'quantitative-analyst', 'research-scientist', 'statistician'],
    experienceLevel: 'senior', searchKeywords: ['matrix', 'data science', 'analytics', 'slate', 'infographic'],
    popularityScore: 82, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'infographic', colorPalette: 'slate' },
  },
  {
    id: 'pipeline',
    name: 'Pipeline',
    description: 'Forest tech terminal for environmental engineers, green-tech and sustainability data professionals.',
    primaryCategory: 'tech-startup', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['sustainability', 'green-tech', 'data', 'engineering'],
    targetRoles: ['data-engineer', 'sustainability-analyst', 'environmental-engineer', 'green-tech'],
    experienceLevel: 'mid', searchKeywords: ['pipeline', 'data', 'sustainability', 'forest', 'green'],
    popularityScore: 71, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'tech', colorPalette: 'forest' },
  },
  {
    id: 'quantum',
    name: 'Quantum',
    description: 'Indigo minimal layout with centred typography. Elevated and understated for research engineers.',
    primaryCategory: 'tech-startup', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['research', 'technology', 'engineering', 'academia'],
    targetRoles: ['research-engineer', 'scientist', 'r-and-d-engineer', 'applied-researcher'],
    experienceLevel: 'senior', searchKeywords: ['quantum', 'research', 'engineer', 'indigo', 'minimal'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'indigo' },
  },

  // ══════════════════════════════════════════════════════════════════
  // CREATIVE-DESIGN  (15 templates)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'canvas',
    name: 'Canvas',
    description: 'Asymmetric clip-path header with diagonal split in rich wine. The signature layout for graphic designers.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['design', 'creative', 'advertising', 'branding'],
    targetRoles: ['graphic-designer', 'visual-designer', 'brand-designer', 'art-director'],
    experienceLevel: 'mid', searchKeywords: ['canvas', 'graphic design', 'creative', 'wine', 'visual'],
    popularityScore: 90, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'creative', colorPalette: 'wine' },
  },
  {
    id: 'palette',
    name: 'Palette',
    description: 'Portfolio-style with project cards and visual grid. Perfect for art directors and creative leads.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['design', 'art-direction', 'advertising', 'creative'],
    targetRoles: ['art-director', 'creative-director', 'design-lead', 'senior-designer'],
    experienceLevel: 'senior', searchKeywords: ['palette', 'art director', 'portfolio', 'plum', 'creative'],
    popularityScore: 85, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'portfolio', colorPalette: 'plum' },
  },
  {
    id: 'studio',
    name: 'Studio',
    description: 'Asymmetric violet creative layout with staggered content for creative directors and agency leads.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['creative', 'agency', 'advertising', 'design'],
    targetRoles: ['creative-director', 'executive-creative-director', 'head-of-design', 'cco'],
    experienceLevel: 'executive', searchKeywords: ['studio', 'creative director', 'agency', 'violet'],
    popularityScore: 83, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'creative', colorPalette: 'violet' },
  },
  {
    id: 'frame',
    name: 'Frame',
    description: 'Portfolio layout in warm rust tones. Designed for photographers, videographers and cinematographers.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['photography', 'video', 'film', 'media'],
    targetRoles: ['photographer', 'videographer', 'cinematographer', 'director-of-photography'],
    experienceLevel: 'mid', searchKeywords: ['frame', 'photography', 'video', 'film', 'rust'],
    popularityScore: 78, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'portfolio', colorPalette: 'rust' },
  },
  {
    id: 'mosaic',
    name: 'Mosaic',
    description: 'Infographic wine layout with visual skill bars and emoji-icon sidebar. For UX and product designers.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['ux', 'product-design', 'ui', 'creative'],
    targetRoles: ['ux-designer', 'ui-designer', 'product-designer', 'interaction-designer'],
    experienceLevel: 'mid', searchKeywords: ['mosaic', 'ux', 'ui', 'product design', 'wine'],
    popularityScore: 86, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'infographic', colorPalette: 'wine' },
  },
  {
    id: 'draft',
    name: 'Draft',
    description: 'Ocean-toned asymmetric layout for illustrators, concept artists and visual storytellers.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['illustration', 'concept-art', 'publishing', 'animation'],
    targetRoles: ['illustrator', 'concept-artist', 'storyboard-artist', 'visual-development'],
    experienceLevel: 'mid', searchKeywords: ['draft', 'illustration', 'concept art', 'ocean', 'artist'],
    popularityScore: 74, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'creative', colorPalette: 'ocean' },
  },
  {
    id: 'exhibit',
    name: 'Exhibit',
    description: 'Portfolio-style in deep burgundy for gallery curators, museum professionals and arts administrators.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['arts', 'museum', 'gallery', 'cultural'],
    targetRoles: ['curator', 'gallery-director', 'arts-administrator', 'cultural-programmer'],
    experienceLevel: 'mid', searchKeywords: ['exhibit', 'curator', 'gallery', 'museum', 'burgundy'],
    popularityScore: 69, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'portfolio', colorPalette: 'burgundy' },
  },
  {
    id: 'layer',
    name: 'Layer',
    description: 'Dark asymmetric charcoal creative layout for motion designers and 3D artists with a bold portfolio.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['motion-design', '3d', 'animation', 'vfx'],
    targetRoles: ['motion-designer', '3d-artist', 'vfx-artist', 'animator'],
    experienceLevel: 'mid', searchKeywords: ['layer', 'motion design', '3d', 'animation', 'charcoal'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'creative', colorPalette: 'charcoal' },
  },
  {
    id: 'hue',
    name: 'Hue',
    description: 'Plum minimal layout with light-weight typography and generous whitespace for brand and identity designers.',
    primaryCategory: 'creative-design', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['branding', 'identity', 'design', 'creative'],
    targetRoles: ['brand-designer', 'identity-designer', 'brand-strategist', 'creative-strategist'],
    experienceLevel: 'mid', searchKeywords: ['hue', 'brand', 'identity', 'plum', 'minimal'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'plum' },
  },
  {
    id: 'vector',
    name: 'Vector',
    description: 'Portfolio violet layout with project showcase grid. The go-to for product and UX designers.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['product-design', 'ux', 'ui', 'design-systems'],
    targetRoles: ['product-designer', 'senior-ux-designer', 'design-systems-designer', 'ux-lead'],
    experienceLevel: 'senior', searchKeywords: ['vector', 'product design', 'ux', 'violet', 'portfolio'],
    popularityScore: 84, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'portfolio', colorPalette: 'violet' },
  },
  {
    id: 'render',
    name: 'Render',
    description: 'Bold wine layout with 900-weight name and filled section bars. For 3D artists and animation directors.',
    primaryCategory: 'creative-design', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['3d', 'animation', 'vfx', 'games'],
    targetRoles: ['3d-artist', 'animation-director', 'vfx-supervisor', 'technical-artist'],
    experienceLevel: 'senior', searchKeywords: ['render', '3d', 'animation', 'wine', 'bold'],
    popularityScore: 73, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'wine' },
  },
  {
    id: 'sketch',
    name: 'Sketch',
    description: 'Teal asymmetric creative layout for UX researchers and service designers who value storytelling.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['ux-research', 'service-design', 'design-strategy'],
    targetRoles: ['ux-researcher', 'service-designer', 'design-strategist', 'design-researcher'],
    experienceLevel: 'mid', searchKeywords: ['sketch', 'ux research', 'service design', 'teal'],
    popularityScore: 75, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'creative', colorPalette: 'teal' },
  },
  {
    id: 'spectrum',
    name: 'Spectrum',
    description: 'Plum infographic layout with visual skill bars for creative technologists bridging design and code.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['creative-technology', 'design', 'development'],
    targetRoles: ['creative-technologist', 'design-developer', 'experience-designer', 'innovation-designer'],
    experienceLevel: 'mid', searchKeywords: ['spectrum', 'creative tech', 'plum', 'infographic'],
    popularityScore: 72, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'infographic', colorPalette: 'plum' },
  },
  {
    id: 'manifest',
    name: 'Manifest',
    description: 'Rust portfolio layout for creative strategists, brand consultants and content directors.',
    primaryCategory: 'creative-design', designStyle: 'creative', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['creative-strategy', 'content', 'branding', 'marketing'],
    targetRoles: ['creative-strategist', 'content-director', 'brand-consultant', 'head-of-content'],
    experienceLevel: 'senior', searchKeywords: ['manifest', 'creative strategy', 'content', 'rust'],
    popularityScore: 70, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'portfolio', colorPalette: 'rust' },
  },
  {
    id: 'etch',
    name: 'Etch',
    description: 'Bold burgundy with filled header bars for print, packaging and graphic production specialists.',
    primaryCategory: 'creative-design', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'visual-first', industryTags: ['print', 'packaging', 'production', 'design'],
    targetRoles: ['print-designer', 'packaging-designer', 'production-artist', 'pre-press-specialist'],
    experienceLevel: 'mid', searchKeywords: ['etch', 'print', 'packaging', 'burgundy', 'bold'],
    popularityScore: 68, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'burgundy' },
  },

  // ══════════════════════════════════════════════════════════════════
  // ACADEMIC-RESEARCH  (10 templates)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'monograph',
    name: 'Monograph',
    description: 'Centred serif academic layout in navy. Publication-ready with proper citation formatting.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['academia', 'research', 'science', 'university'],
    targetRoles: ['professor', 'researcher', 'postdoc', 'scientist'],
    experienceLevel: 'senior', searchKeywords: ['monograph', 'academic', 'professor', 'research', 'navy'],
    popularityScore: 86, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'academic', colorPalette: 'navy' },
  },
  {
    id: 'thesis',
    name: 'Thesis',
    description: 'Teal serif academic layout with education-first prominence. Designed for PhD students and postdocs.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['academia', 'research', 'phd', 'graduate'],
    targetRoles: ['phd-student', 'postdoc', 'research-fellow', 'graduate-researcher'],
    experienceLevel: 'entry', searchKeywords: ['thesis', 'phd', 'graduate', 'academic', 'teal'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'academic', colorPalette: 'teal' },
  },
  {
    id: 'annals',
    name: 'Annals',
    description: 'Classic navy serif with centred header and underlined section dividers for humanities scholars.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['humanities', 'history', 'literature', 'philosophy'],
    targetRoles: ['historian', 'literature-professor', 'philosopher', 'cultural-scholar'],
    experienceLevel: 'senior', searchKeywords: ['annals', 'humanities', 'history', 'navy', 'classic'],
    popularityScore: 73, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'navy' },
  },
  {
    id: 'empirical',
    name: 'Empirical',
    description: 'Slate academic layout for social scientists and quantitative researchers with extensive publications.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['social-science', 'economics', 'psychology', 'research'],
    targetRoles: ['social-scientist', 'economist', 'psychologist', 'political-scientist'],
    experienceLevel: 'senior', searchKeywords: ['empirical', 'social science', 'economics', 'slate', 'academic'],
    popularityScore: 77, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'academic', colorPalette: 'slate' },
  },
  {
    id: 'codex',
    name: 'Codex',
    description: 'Classic charcoal serif for literature, linguistics and language studies academics.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['linguistics', 'literature', 'language', 'humanities'],
    targetRoles: ['linguist', 'literature-professor', 'language-researcher', 'translator'],
    experienceLevel: 'senior', searchKeywords: ['codex', 'linguistics', 'literature', 'charcoal', 'classic'],
    popularityScore: 70, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'charcoal' },
  },
  {
    id: 'symposium',
    name: 'Symposium',
    description: 'Two-column ocean sidebar layout for conference speakers and interdisciplinary researchers.',
    primaryCategory: 'academic-research', designStyle: 'modern', pageLength: 'extended',
    atsCompatibility: 'ats-friendly', industryTags: ['academia', 'research', 'conference', 'interdisciplinary'],
    targetRoles: ['conference-speaker', 'research-director', 'department-head', 'visiting-scholar'],
    experienceLevel: 'executive', searchKeywords: ['symposium', 'conference', 'speaker', 'ocean', 'sidebar'],
    popularityScore: 74, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'ocean' },
  },
  {
    id: 'discourse',
    name: 'Discourse',
    description: 'Forest academic layout for philosophy, ethics and critical theory scholars.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['philosophy', 'ethics', 'theory', 'humanities'],
    targetRoles: ['philosopher', 'ethicist', 'critical-theorist', 'political-philosopher'],
    experienceLevel: 'senior', searchKeywords: ['discourse', 'philosophy', 'ethics', 'forest', 'academic'],
    popularityScore: 67, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'academic', colorPalette: 'forest' },
  },
  {
    id: 'postulate',
    name: 'Postulate',
    description: 'Clean single-column teal layout for STEM researchers, physicists and mathematicians.',
    primaryCategory: 'academic-research', designStyle: 'professional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['stem', 'physics', 'mathematics', 'chemistry'],
    targetRoles: ['physicist', 'mathematician', 'chemist', 'stem-researcher'],
    experienceLevel: 'senior', searchKeywords: ['postulate', 'stem', 'physics', 'mathematics', 'teal'],
    popularityScore: 72, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'single-standard', colorPalette: 'teal' },
  },
  {
    id: 'treatise',
    name: 'Treatise',
    description: 'Classic slate serif layout for academic administrators, deans and university leadership.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['academia', 'administration', 'university', 'education'],
    targetRoles: ['dean', 'department-chair', 'academic-director', 'registrar'],
    experienceLevel: 'executive', searchKeywords: ['treatise', 'dean', 'academic administration', 'slate'],
    popularityScore: 68, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'slate' },
  },
  {
    id: 'lexicon',
    name: 'Lexicon',
    description: 'Indigo academic layout for information scientists, librarians and knowledge management professionals.',
    primaryCategory: 'academic-research', designStyle: 'traditional', pageLength: 'extended',
    atsCompatibility: 'ats-safe', industryTags: ['library', 'information-science', 'knowledge-management'],
    targetRoles: ['librarian', 'information-scientist', 'archivist', 'knowledge-manager'],
    experienceLevel: 'mid', searchKeywords: ['lexicon', 'library', 'information science', 'indigo', 'academic'],
    popularityScore: 65, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'academic', colorPalette: 'indigo' },
  },

  // ══════════════════════════════════════════════════════════════════
  // ENTRY-STUDENT  (15 templates)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'debut',
    name: 'Debut',
    description: 'Timeline layout in royal blue that showcases career progression and academic milestones for new graduates.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'business', 'consulting', 'finance'],
    targetRoles: ['graduate', 'analyst', 'associate', 'junior-developer'],
    experienceLevel: 'entry', searchKeywords: ['debut', 'graduate', 'entry level', 'timeline', 'royal'],
    popularityScore: 88, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'timeline', colorPalette: 'royal' },
  },
  {
    id: 'envoy',
    name: 'Envoy',
    description: 'Contemporary royal-blue band header. The professional first impression for ambitious young professionals.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['business', 'consulting', 'finance', 'corporate'],
    targetRoles: ['graduate-trainee', 'junior-analyst', 'associate', 'programme-associate'],
    experienceLevel: 'entry', searchKeywords: ['envoy', 'graduate', 'contemporary', 'royal', 'professional'],
    popularityScore: 84, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'royal' },
  },
  {
    id: 'scout',
    name: 'Scout',
    description: 'Clean teal minimal layout. Ideal for internship applications and first-job seekers in any field.',
    primaryCategory: 'entry-student', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'business', 'engineering', 'any'],
    targetRoles: ['intern', 'graduate', 'junior-associate', 'trainee'],
    experienceLevel: 'entry', searchKeywords: ['scout', 'intern', 'entry level', 'teal', 'minimal'],
    popularityScore: 82, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'teal' },
  },
  {
    id: 'prospect',
    name: 'Prospect',
    description: 'Indigo timeline layout for career changers who want to visually reframe their professional journey.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'consulting', 'any'],
    targetRoles: ['career-changer', 'transitioning-professional', 'bootcamp-graduate'],
    experienceLevel: 'entry', searchKeywords: ['prospect', 'career change', 'timeline', 'indigo', 'transition'],
    popularityScore: 79, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'timeline', colorPalette: 'indigo' },
  },
  {
    id: 'initiate',
    name: 'Initiate',
    description: 'Bold ocean layout with filled section bars that helps entry-level candidates punch above their weight.',
    primaryCategory: 'entry-student', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'startup', 'any'],
    targetRoles: ['junior-developer', 'graduate-engineer', 'associate-analyst', 'junior-pm'],
    experienceLevel: 'entry', searchKeywords: ['initiate', 'entry level', 'bold', 'ocean', 'junior'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'ocean' },
  },
  {
    id: 'launch',
    name: 'Launch',
    description: 'Contemporary emerald band for new-grad tech professionals entering the startup ecosystem.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['technology', 'startup', 'software'],
    targetRoles: ['junior-developer', 'graduate-engineer', 'junior-pm', 'graduate-analyst'],
    experienceLevel: 'entry', searchKeywords: ['launch', 'startup', 'grad tech', 'emerald', 'contemporary'],
    popularityScore: 81, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'emerald' },
  },
  {
    id: 'ascend',
    name: 'Ascend',
    description: 'Violet timeline layout for ambitious graduates mapping out their career journey with pride.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['any', 'consulting', 'finance', 'technology'],
    targetRoles: ['graduate', 'associate', 'management-trainee', 'analyst'],
    experienceLevel: 'entry', searchKeywords: ['ascend', 'graduate', 'timeline', 'violet', 'ambitious'],
    popularityScore: 77, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'timeline', colorPalette: 'violet' },
  },
  {
    id: 'kindle',
    name: 'Kindle',
    description: 'Warm rust minimal layout for creative and arts students entering the workforce for the first time.',
    primaryCategory: 'entry-student', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['creative', 'arts', 'media', 'marketing'],
    targetRoles: ['junior-designer', 'marketing-assistant', 'content-creator', 'communications-assistant'],
    experienceLevel: 'entry', searchKeywords: ['kindle', 'creative entry', 'minimal', 'rust', 'arts'],
    popularityScore: 73, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'rust' },
  },
  {
    id: 'trailhead',
    name: 'Trailhead',
    description: 'Forest two-column sidebar for environmental, sustainability and nonprofit-sector graduates.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['nonprofit', 'sustainability', 'environment', 'social-impact'],
    targetRoles: ['sustainability-analyst', 'environmental-officer', 'nonprofit-associate', 'programme-coordinator'],
    experienceLevel: 'entry', searchKeywords: ['trailhead', 'sustainability', 'nonprofit', 'forest', 'sidebar'],
    popularityScore: 71, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'forest' },
  },
  {
    id: 'origin',
    name: 'Origin',
    description: 'Royal bold-modern layout with impact typography. Designed for MBA and business school graduates.',
    primaryCategory: 'entry-student', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['business', 'consulting', 'finance', 'mba'],
    targetRoles: ['mba-graduate', 'consultant', 'business-analyst', 'associate'],
    experienceLevel: 'entry', searchKeywords: ['origin', 'mba', 'business school', 'royal', 'bold'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'royal' },
  },
  {
    id: 'breakthrough',
    name: 'Breakthrough',
    description: 'Teal timeline layout for healthcare and nursing students entering clinical roles.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['healthcare', 'nursing', 'medical', 'clinical'],
    targetRoles: ['graduate-nurse', 'junior-clinician', 'medical-officer', 'health-analyst'],
    experienceLevel: 'entry', searchKeywords: ['breakthrough', 'healthcare', 'nursing', 'teal', 'timeline'],
    popularityScore: 74, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'timeline', colorPalette: 'teal' },
  },
  {
    id: 'folio',
    name: 'Folio',
    description: 'Graphite minimal layout for design, arts and architecture students compiling their first portfolio-adjacent CV.',
    primaryCategory: 'entry-student', designStyle: 'minimal', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['design', 'architecture', 'arts', 'creative'],
    targetRoles: ['design-graduate', 'junior-designer', 'architecture-graduate', 'creative-assistant'],
    experienceLevel: 'entry', searchKeywords: ['folio', 'design student', 'portfolio', 'graphite', 'minimal'],
    popularityScore: 72, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'minimal', colorPalette: 'graphite' },
  },
  {
    id: 'pathway',
    name: 'Pathway',
    description: 'Navy contemporary band for liberal arts and humanities graduates entering professional roles.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['any', 'government', 'nonprofit', 'communications'],
    targetRoles: ['policy-assistant', 'communications-coordinator', 'programme-associate', 'editorial-assistant'],
    experienceLevel: 'entry', searchKeywords: ['pathway', 'liberal arts', 'humanities', 'navy', 'contemporary'],
    popularityScore: 75, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'contemporary', colorPalette: 'navy' },
  },
  {
    id: 'spark',
    name: 'Spark',
    description: 'Burgundy bold-modern layout for sales, marketing and communications graduates who want to make an impression.',
    primaryCategory: 'entry-student', designStyle: 'bold', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['sales', 'marketing', 'communications', 'media'],
    targetRoles: ['sales-associate', 'marketing-assistant', 'communications-assistant', 'account-coordinator'],
    experienceLevel: 'entry', searchKeywords: ['spark', 'sales entry', 'marketing', 'burgundy', 'bold'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'bold-modern', colorPalette: 'burgundy' },
  },
  {
    id: 'springboard',
    name: 'Springboard',
    description: 'Ocean timeline layout for engineering and STEM graduates with a strong project portfolio to showcase.',
    primaryCategory: 'entry-student', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['engineering', 'stem', 'technology', 'manufacturing'],
    targetRoles: ['graduate-engineer', 'junior-engineer', 'mechanical-engineer-graduate', 'chemical-engineer'],
    experienceLevel: 'entry', searchKeywords: ['springboard', 'engineering', 'stem', 'ocean', 'graduate'],
    popularityScore: 78, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'timeline', colorPalette: 'ocean' },
  },

  // ══════════════════════════════════════════════════════════════════
  // EXECUTIVE-LEADERSHIP  (15 templates)
  // ══════════════════════════════════════════════════════════════════

  {
    id: 'apex',
    name: 'Apex',
    description: 'The executive standard. Formal serif layout in charcoal for CEOs and C-suite leaders.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['executive', 'corporate', 'leadership', 'board'],
    targetRoles: ['ceo', 'president', 'managing-director', 'chief-executive'],
    experienceLevel: 'executive', searchKeywords: ['apex', 'ceo', 'executive', 'charcoal', 'formal'],
    popularityScore: 93, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'charcoal' },
  },
  {
    id: 'legacy',
    name: 'Legacy',
    description: 'Navy classic serif with centred header — the chairman\'s choice. Built for board-level presence.',
    primaryCategory: 'executive-leadership', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['board', 'executive', 'governance', 'finance'],
    targetRoles: ['chairman', 'board-member', 'non-executive-director', 'senior-partner'],
    experienceLevel: 'executive', searchKeywords: ['legacy', 'chairman', 'board', 'navy', 'classic'],
    popularityScore: 87, isFeatured: true, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'navy' },
  },
  {
    id: 'exemplar',
    name: 'Exemplar',
    description: 'Slate executive layout for COOs, VP-Operations and general managers driving organisational excellence.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['operations', 'executive', 'leadership', 'corporate'],
    targetRoles: ['coo', 'vp-operations', 'general-manager', 'operations-executive'],
    experienceLevel: 'executive', searchKeywords: ['exemplar', 'coo', 'operations', 'slate', 'executive'],
    popularityScore: 83, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'slate' },
  },
  {
    id: 'authority',
    name: 'Authority',
    description: 'Charcoal executive layout projecting financial gravitas for CFOs and finance executives.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['finance', 'executive', 'banking', 'investment'],
    targetRoles: ['cfo', 'finance-executive', 'treasurer', 'finance-director'],
    experienceLevel: 'executive', searchKeywords: ['authority', 'cfo', 'finance', 'charcoal', 'executive'],
    popularityScore: 85, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'charcoal' },
  },
  {
    id: 'directive',
    name: 'Directive',
    description: 'Classic slate serif for CTOs and technology executives who value substance over spectacle.',
    primaryCategory: 'executive-leadership', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['technology', 'executive', 'digital', 'leadership'],
    targetRoles: ['cto', 'chief-digital-officer', 'vp-technology', 'technology-executive'],
    experienceLevel: 'executive', searchKeywords: ['directive', 'cto', 'technology', 'slate', 'classic'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'slate' },
  },
  {
    id: 'provenance',
    name: 'Provenance',
    description: 'Navy executive layout for founders, entrepreneurs and venture-backed company leaders.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['entrepreneurship', 'startup', 'venture', 'executive'],
    targetRoles: ['founder', 'co-founder', 'entrepreneur', 'venture-executive'],
    experienceLevel: 'executive', searchKeywords: ['provenance', 'founder', 'entrepreneur', 'navy', 'executive'],
    popularityScore: 82, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'navy' },
  },
  {
    id: 'stature',
    name: 'Stature',
    description: 'Ultra-compact charcoal layout that distils a career of executive achievement into a single powerful page.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['executive', 'corporate', 'board', 'leadership'],
    targetRoles: ['senior-executive', 'managing-director', 'executive-director', 'partner'],
    experienceLevel: 'executive', searchKeywords: ['stature', 'compact', 'executive', 'charcoal', 'one page'],
    popularityScore: 78, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'compact', colorPalette: 'charcoal' },
  },
  {
    id: 'command',
    name: 'Command',
    description: 'Professional graphite accent-bar layout for division presidents and senior business leaders.',
    primaryCategory: 'executive-leadership', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['corporate', 'executive', 'management', 'leadership'],
    targetRoles: ['division-president', 'group-ceo', 'senior-vp', 'executive-vp'],
    experienceLevel: 'executive', searchKeywords: ['command', 'division president', 'graphite', 'professional'],
    popularityScore: 76, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'graphite' },
  },
  {
    id: 'marquee',
    name: 'Marquee',
    description: 'Burgundy executive layout commanding attention. Designed for CMOs and senior marketing executives.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['marketing', 'executive', 'brand', 'creative'],
    targetRoles: ['cmo', 'marketing-executive', 'vp-marketing', 'chief-brand-officer'],
    experienceLevel: 'executive', searchKeywords: ['marquee', 'cmo', 'marketing', 'burgundy', 'executive'],
    popularityScore: 81, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'burgundy' },
  },
  {
    id: 'influence',
    name: 'Influence',
    description: 'Charcoal two-column sidebar layout for CHROs and people executives with broad organisational scope.',
    primaryCategory: 'executive-leadership', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['human-resources', 'people', 'executive', 'talent'],
    targetRoles: ['chro', 'chief-people-officer', 'hr-executive', 'vp-people'],
    experienceLevel: 'executive', searchKeywords: ['influence', 'chro', 'people', 'charcoal', 'sidebar'],
    popularityScore: 79, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'two-sidebar', colorPalette: 'charcoal' },
  },
  {
    id: 'conclave',
    name: 'Conclave',
    description: 'Forest classic serif for non-profit CEOs, social enterprise leaders and mission-driven executives.',
    primaryCategory: 'executive-leadership', designStyle: 'traditional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['nonprofit', 'social-enterprise', 'foundation', 'ngo'],
    targetRoles: ['nonprofit-ceo', 'executive-director', 'foundation-president', 'ngo-leader'],
    experienceLevel: 'executive', searchKeywords: ['conclave', 'nonprofit', 'ngo', 'forest', 'classic'],
    popularityScore: 74, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'classic', colorPalette: 'forest' },
  },
  {
    id: 'pillar',
    name: 'Pillar',
    description: 'Slate executive format for private equity partners, investment directors and fund managers.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['private-equity', 'investment', 'finance', 'executive'],
    targetRoles: ['private-equity-partner', 'investment-director', 'fund-manager', 'portfolio-director'],
    experienceLevel: 'executive', searchKeywords: ['pillar', 'private equity', 'investment', 'slate'],
    popularityScore: 82, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'slate' },
  },
  {
    id: 'continuum',
    name: 'Continuum',
    description: 'Navy professional accent-bar layout for managing directors and senior partners at professional firms.',
    primaryCategory: 'executive-leadership', designStyle: 'professional', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['professional-services', 'consulting', 'law', 'accounting'],
    targetRoles: ['managing-director', 'senior-partner', 'principal', 'director'],
    experienceLevel: 'executive', searchKeywords: ['continuum', 'managing director', 'partner', 'navy', 'professional'],
    popularityScore: 80, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'professional', colorPalette: 'navy' },
  },
  {
    id: 'chronicle',
    name: 'Chronicle',
    description: 'Charcoal timeline layout for executives with a rich career narrative spanning multiple industries.',
    primaryCategory: 'executive-leadership', designStyle: 'modern', pageLength: 'standard',
    atsCompatibility: 'ats-friendly', industryTags: ['executive', 'leadership', 'corporate', 'board'],
    targetRoles: ['executive-director', 'cxo', 'senior-executive', 'board-advisor'],
    experienceLevel: 'executive', searchKeywords: ['chronicle', 'executive', 'timeline', 'charcoal', 'career narrative'],
    popularityScore: 77, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: false,
    templateConfig: { layoutType: 'timeline', colorPalette: 'charcoal' },
  },
  {
    id: 'empire',
    name: 'Empire',
    description: 'Navy executive layout commanding the room. For Senior VPs and EVPs leading global organisations.',
    primaryCategory: 'executive-leadership', designStyle: 'executive', pageLength: 'standard',
    atsCompatibility: 'ats-safe', industryTags: ['executive', 'global', 'corporate', 'leadership'],
    targetRoles: ['evp', 'svp', 'global-executive', 'group-president'],
    experienceLevel: 'executive', searchKeywords: ['empire', 'evp', 'svp', 'navy', 'global', 'executive'],
    popularityScore: 84, isFeatured: false, supportedFormats: ['pdf', 'docx'], usageCount: 0,
    isPremium: false, isDefault: false, isAtsSafe: true,
    templateConfig: { layoutType: 'executive', colorPalette: 'navy' },
  },

];

export async function seedTemplates() {
  console.log('🌱 Seeding 100 premium templates...');

  // Preserve the 3 original legacy templates; replace everything else
  await prisma.resumeTemplate.deleteMany({
    where: { id: { notIn: ['professional', 'modern', 'executive'] } },
  });

  let created = 0;
  for (const seed of templateSeeds) {
    await prisma.resumeTemplate.upsert({
      where: { id: seed.id },
      update: seed,
      create: seed,
    });
    created++;
  }

  console.log(`✅ ${created} premium templates seeded successfully.`);
  console.log('   Layouts used: 15 distinct layout types across 6 categories.');
}
