/**
 * Template Database Seed Script
 * Seeds all 80 resume templates into the ResumeTemplate table
 *
 * Distribution:
 * - ATS-Professional: 15 templates
 * - Entry-Student: 15 templates
 * - Tech-Startup: 15 templates
 * - Creative-Design: 15 templates
 * - Academic-Research: 10 templates
 * - Executive-Leadership: 10 templates
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Template seed data organized by category
const templateSeeds = [
  // ============================================================================
  // ATS-PROFESSIONAL CATEGORY (15 templates)
  // ============================================================================
  {
    id: 'corporate-standard',
    name: 'Corporate Standard',
    description: 'Clean, professional template optimized for ATS systems in corporate environments',
    primaryCategory: 'ats-professional',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['finance', 'banking', 'corporate', 'consulting'],
    targetRoles: ['business-analyst', 'financial-analyst', 'consultant', 'manager'],
    experienceLevel: 'mid',
    searchKeywords: ['corporate', 'professional', 'ats', 'business', 'finance'],
    popularityScore: 95,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: true,
    isAtsSafe: true,
    templateConfig: {
      layout: 'single-column',
      headerStyle: 'centered',
      sectionStyle: 'underline',
      colorPalette: 'professional',
    },
  },
  {
    id: 'finance-professional',
    name: 'Finance Professional',
    description: 'Sophisticated template tailored for finance and accounting roles',
    primaryCategory: 'ats-professional',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['finance', 'accounting', 'banking', 'investment'],
    targetRoles: ['financial-analyst', 'accountant', 'auditor', 'cfa'],
    experienceLevel: 'mid',
    searchKeywords: ['finance', 'accounting', 'cpa', 'financial analysis'],
    popularityScore: 88,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'legal-traditional',
    name: 'Legal Traditional',
    description: 'Conservative template designed for legal professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['legal', 'law', 'paralegal', 'compliance'],
    targetRoles: ['attorney', 'paralegal', 'legal-counsel', 'compliance-officer'],
    experienceLevel: 'senior',
    searchKeywords: ['legal', 'law', 'attorney', 'paralegal', 'juris doctor'],
    popularityScore: 82,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'healthcare-clean',
    name: 'Healthcare Clean',
    description: 'Professional template for healthcare and medical professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['healthcare', 'medical', 'nursing', 'clinical'],
    targetRoles: ['nurse', 'physician', 'medical-assistant', 'healthcare-admin'],
    experienceLevel: 'mid',
    searchKeywords: ['healthcare', 'medical', 'nursing', 'clinical', 'patient care'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'consulting-classic',
    name: 'Consulting Classic',
    description: 'Polished template for management consulting roles',
    primaryCategory: 'ats-professional',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['consulting', 'business', 'strategy', 'management'],
    targetRoles: ['consultant', 'business-analyst', 'strategy-consultant', 'management-consultant'],
    experienceLevel: 'mid',
    searchKeywords: ['consulting', 'strategy', 'business analysis', 'mba'],
    popularityScore: 90,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'executive-formal',
    name: 'Executive Formal',
    description: 'Distinguished template for senior executives',
    primaryCategory: 'ats-professional',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['executive', 'management', 'leadership', 'c-suite'],
    targetRoles: ['ceo', 'cfo', 'coo', 'vp', 'director'],
    experienceLevel: 'executive',
    searchKeywords: ['executive', 'leadership', 'c-suite', 'senior management'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'business-elegant',
    name: 'Business Elegant',
    description: 'Refined template for business professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['business', 'corporate', 'management', 'operations'],
    targetRoles: ['business-manager', 'operations-manager', 'project-manager'],
    experienceLevel: 'mid',
    searchKeywords: ['business', 'management', 'operations', 'project management'],
    popularityScore: 84,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'banking-conservative',
    name: 'Banking Conservative',
    description: 'Traditional template for banking and financial services',
    primaryCategory: 'ats-professional',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['banking', 'finance', 'investment', 'wealth-management'],
    targetRoles: ['banker', 'investment-banker', 'wealth-advisor', 'relationship-manager'],
    experienceLevel: 'mid',
    searchKeywords: ['banking', 'finance', 'investment', 'wealth management'],
    popularityScore: 80,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'insurance-professional',
    name: 'Insurance Professional',
    description: 'Professional template for insurance industry roles',
    primaryCategory: 'ats-professional',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['insurance', 'risk-management', 'underwriting', 'claims'],
    targetRoles: ['underwriter', 'insurance-agent', 'claims-adjuster', 'risk-analyst'],
    experienceLevel: 'mid',
    searchKeywords: ['insurance', 'underwriting', 'risk management', 'claims'],
    popularityScore: 76,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'accounting-standard',
    name: 'Accounting Standard',
    description: 'Clean template for accounting professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['accounting', 'finance', 'audit', 'tax'],
    targetRoles: ['accountant', 'auditor', 'tax-specialist', 'controller'],
    experienceLevel: 'mid',
    searchKeywords: ['accounting', 'cpa', 'audit', 'gaap', 'financial reporting'],
    popularityScore: 83,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'corporate-modern',
    name: 'Corporate Modern',
    description: 'Contemporary take on professional corporate template',
    primaryCategory: 'ats-professional',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['corporate', 'business', 'technology', 'management'],
    targetRoles: ['business-analyst', 'product-manager', 'operations-manager'],
    experienceLevel: 'mid',
    searchKeywords: ['corporate', 'business', 'modern professional', 'management'],
    popularityScore: 87,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'finance-executive',
    name: 'Finance Executive',
    description: 'Executive-level template for senior finance professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['finance', 'executive', 'c-suite', 'banking'],
    targetRoles: ['cfo', 'vp-finance', 'finance-director', 'treasurer'],
    experienceLevel: 'executive',
    searchKeywords: ['finance executive', 'cfo', 'financial leadership', 'strategic finance'],
    popularityScore: 81,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'legal-minimal',
    name: 'Legal Minimal',
    description: 'Modern minimalist template for legal professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['legal', 'law', 'corporate-law', 'litigation'],
    targetRoles: ['attorney', 'legal-associate', 'legal-counsel', 'litigator'],
    experienceLevel: 'mid',
    searchKeywords: ['legal', 'attorney', 'law', 'litigation', 'corporate law'],
    popularityScore: 79,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'consulting-refined',
    name: 'Consulting Refined',
    description: 'Refined template for experienced consultants',
    primaryCategory: 'ats-professional',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['consulting', 'strategy', 'management', 'business'],
    targetRoles: ['senior-consultant', 'principal-consultant', 'engagement-manager'],
    experienceLevel: 'senior',
    searchKeywords: ['consulting', 'strategy', 'management consulting', 'senior consultant'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'professional-elite',
    name: 'Professional Elite',
    description: 'Premium template for top-tier professionals',
    primaryCategory: 'ats-professional',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['executive', 'corporate', 'consulting', 'finance'],
    targetRoles: ['senior-executive', 'partner', 'director', 'vp'],
    experienceLevel: 'executive',
    searchKeywords: ['elite professional', 'executive', 'senior leadership', 'c-level'],
    popularityScore: 88,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },

  // ============================================================================
  // ENTRY-STUDENT CATEGORY (15 templates)
  // ============================================================================
  {
    id: 'graduate-fresh',
    name: 'Graduate Fresh',
    description: 'Modern template for recent graduates entering the workforce',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['education', 'entry-level', 'recent-graduate'],
    targetRoles: ['entry-level', 'associate', 'junior', 'graduate-trainee'],
    experienceLevel: 'entry',
    searchKeywords: ['graduate', 'entry level', 'recent graduate', 'college'],
    popularityScore: 92,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'student-clean',
    name: 'Student Clean',
    description: 'Clean, simple template for current students',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['education', 'student', 'internship'],
    targetRoles: ['intern', 'student-worker', 'co-op'],
    experienceLevel: 'entry',
    searchKeywords: ['student', 'internship', 'college student', 'university'],
    popularityScore: 89,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'intern-ready',
    name: 'Intern Ready',
    description: 'Optimized template for internship applications',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['internship', 'student', 'entry-level'],
    targetRoles: ['intern', 'summer-intern', 'co-op-student'],
    experienceLevel: 'entry',
    searchKeywords: ['internship', 'student', 'summer program', 'co-op'],
    popularityScore: 91,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'entry-professional',
    name: 'Entry Professional',
    description: 'Professional template for entry-level positions',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-safe',
    industryTags: ['entry-level', 'business', 'corporate'],
    targetRoles: ['entry-level', 'associate', 'assistant'],
    experienceLevel: 'entry',
    searchKeywords: ['entry level', 'first job', 'associate', 'junior'],
    popularityScore: 88,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'career-starter',
    name: 'Career Starter',
    description: 'Template designed for those starting their career journey',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['entry-level', 'career-change', 'recent-graduate'],
    targetRoles: ['entry-level', 'trainee', 'junior'],
    experienceLevel: 'entry',
    searchKeywords: ['career starter', 'first job', 'entry level', 'new professional'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'recent-graduate',
    name: 'Recent Graduate',
    description: 'Tailored for new graduates with limited work experience',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['recent-graduate', 'entry-level', 'education'],
    targetRoles: ['graduate-trainee', 'entry-level', 'associate'],
    experienceLevel: 'entry',
    searchKeywords: ['recent graduate', 'bachelors', 'new grad', 'college graduate'],
    popularityScore: 90,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'college-student',
    name: 'College Student',
    description: 'Perfect for current college students seeking opportunities',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['student', 'college', 'internship'],
    targetRoles: ['student-intern', 'part-time', 'student-worker'],
    experienceLevel: 'entry',
    searchKeywords: ['college student', 'undergraduate', 'student', 'campus'],
    popularityScore: 87,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'first-job',
    name: 'First Job',
    description: 'Designed for those applying to their first professional role',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-safe',
    industryTags: ['entry-level', 'first-job', 'recent-graduate'],
    targetRoles: ['entry-level', 'trainee', 'junior'],
    experienceLevel: 'entry',
    searchKeywords: ['first job', 'entry level', 'beginner', 'no experience'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'entry-level',
    name: 'Entry Level',
    description: 'Straightforward template for entry-level job seekers',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-safe',
    industryTags: ['entry-level', 'business', 'general'],
    targetRoles: ['entry-level', 'junior', 'assistant'],
    experienceLevel: 'entry',
    searchKeywords: ['entry level', 'junior', 'assistant', 'beginner'],
    popularityScore: 84,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'career-change',
    name: 'Career Change',
    description: 'Template for professionals transitioning to new careers',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['career-change', 'transition', 'entry-level'],
    targetRoles: ['career-changer', 'entry-level', 'associate'],
    experienceLevel: 'entry',
    searchKeywords: ['career change', 'transition', 'new field', 'career pivot'],
    popularityScore: 83,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'internship',
    name: 'Internship',
    description: 'Specialized template for internship seekers',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['internship', 'student', 'education'],
    targetRoles: ['intern', 'summer-intern', 'student-intern'],
    experienceLevel: 'entry',
    searchKeywords: ['internship', 'summer', 'student program', 'intern'],
    popularityScore: 90,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'junior-professional',
    name: 'Junior Professional',
    description: 'Template for junior-level professionals with 0-2 years experience',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-safe',
    industryTags: ['entry-level', 'junior', 'business'],
    targetRoles: ['junior', 'associate', 'assistant'],
    experienceLevel: 'entry',
    searchKeywords: ['junior', 'associate', '1 year experience', 'early career'],
    popularityScore: 82,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'new-graduate',
    name: 'New Graduate',
    description: 'Fresh template for brand new graduates',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['recent-graduate', 'education', 'entry-level'],
    targetRoles: ['new-grad', 'entry-level', 'trainee'],
    experienceLevel: 'entry',
    searchKeywords: ['new graduate', 'fresh graduate', 'class of 2024', 'new grad'],
    popularityScore: 88,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'career-launch',
    name: 'Career Launch',
    description: 'Dynamic template to launch your professional career',
    primaryCategory: 'entry-student',
    designStyle: 'modern',
    pageLength: 'one-page',
    atsCompatibility: 'ats-friendly',
    industryTags: ['entry-level', 'career-start', 'recent-graduate'],
    targetRoles: ['entry-level', 'associate', 'trainee'],
    experienceLevel: 'entry',
    searchKeywords: ['career launch', 'first career', 'professional start', 'entry'],
    popularityScore: 81,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'freshman',
    name: 'Freshman',
    description: 'Basic template for first-year students and very early career',
    primaryCategory: 'entry-student',
    designStyle: 'minimal',
    pageLength: 'one-page',
    atsCompatibility: 'ats-safe',
    industryTags: ['student', 'education', 'first-year'],
    targetRoles: ['student', 'intern', 'volunteer'],
    experienceLevel: 'entry',
    searchKeywords: ['freshman', 'first year', 'student', 'beginner'],
    popularityScore: 78,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },

  // ============================================================================
  // TECH-STARTUP CATEGORY (15 templates)
  // ============================================================================
  {
    id: 'developer-minimal',
    name: 'Developer Minimal',
    description: 'Clean, minimalist single-column design for developers',
    primaryCategory: 'tech-startup',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['software', 'technology', 'engineering', 'development'],
    targetRoles: ['software-engineer', 'developer', 'programmer', 'full-stack'],
    experienceLevel: 'mid',
    searchKeywords: ['developer', 'software engineer', 'programming', 'coding'],
    popularityScore: 94,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'tech-modern',
    name: 'Tech Modern',
    description: 'Modern design with cyan/teal palette for tech professionals',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['technology', 'software', 'startup', 'it'],
    targetRoles: ['software-engineer', 'tech-lead', 'developer'],
    experienceLevel: 'mid',
    searchKeywords: ['tech', 'modern tech', 'software', 'technology'],
    popularityScore: 91,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'engineer-clean',
    name: 'Engineer Clean',
    description: 'Professional clean design for engineers',
    primaryCategory: 'tech-startup',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['engineering', 'software', 'technology'],
    targetRoles: ['software-engineer', 'systems-engineer', 'platform-engineer'],
    experienceLevel: 'mid',
    searchKeywords: ['engineer', 'software engineering', 'systems', 'technical'],
    popularityScore: 89,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'startup-bold',
    name: 'Startup Bold',
    description: 'Bold two-column sidebar design for startup roles',
    primaryCategory: 'tech-startup',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['startup', 'technology', 'entrepreneurship'],
    targetRoles: ['startup-engineer', 'founding-engineer', 'early-employee'],
    experienceLevel: 'mid',
    searchKeywords: ['startup', 'bold', 'entrepreneurial', 'innovative'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    description: 'Professional template for product managers',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['product-management', 'technology', 'startup', 'business'],
    targetRoles: ['product-manager', 'senior-pm', 'product-owner'],
    experienceLevel: 'mid',
    searchKeywords: ['product manager', 'pm', 'product owner', 'product lead'],
    popularityScore: 92,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'code-professional',
    name: 'Code Professional',
    description: 'Professional template with code-style accents',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['software', 'development', 'programming', 'technology'],
    targetRoles: ['software-developer', 'programmer', 'engineer'],
    experienceLevel: 'mid',
    searchKeywords: ['coding', 'programming', 'developer', 'software'],
    popularityScore: 88,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'data-science',
    name: 'Data Science',
    description: 'Specialized template for data scientists',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['data-science', 'analytics', 'machine-learning', 'ai'],
    targetRoles: ['data-scientist', 'ml-engineer', 'data-analyst'],
    experienceLevel: 'mid',
    searchKeywords: ['data science', 'machine learning', 'analytics', 'python'],
    popularityScore: 90,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'tech-executive',
    name: 'Tech Executive',
    description: 'Executive-style template for technical leaders',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['technology', 'executive', 'leadership', 'management'],
    targetRoles: ['cto', 'vp-engineering', 'tech-director'],
    experienceLevel: 'executive',
    searchKeywords: ['tech executive', 'cto', 'vp engineering', 'tech leadership'],
    popularityScore: 84,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'startup-casual',
    name: 'Startup Casual',
    description: 'Casual two-column template for startup culture',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['startup', 'technology', 'entrepreneurship'],
    targetRoles: ['startup-employee', 'early-stage', 'generalist'],
    experienceLevel: 'mid',
    searchKeywords: ['startup', 'casual', 'entrepreneurial', 'flexible'],
    popularityScore: 82,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'developer-pro',
    name: 'Developer Pro',
    description: 'Professional two-column for experienced developers',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['software', 'development', 'engineering'],
    targetRoles: ['senior-developer', 'staff-engineer', 'principal-engineer'],
    experienceLevel: 'senior',
    searchKeywords: ['senior developer', 'experienced engineer', 'staff engineer'],
    popularityScore: 87,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    description: 'Classic single-column template for software engineers',
    primaryCategory: 'tech-startup',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['software', 'engineering', 'development', 'technology'],
    targetRoles: ['software-engineer', 'swe', 'backend-engineer', 'frontend-engineer'],
    experienceLevel: 'mid',
    searchKeywords: ['software engineer', 'swe', 'engineering', 'developer'],
    popularityScore: 93,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'full-stack',
    name: 'Full Stack',
    description: 'Balanced template for full-stack developers',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['full-stack', 'software', 'web-development'],
    targetRoles: ['full-stack-developer', 'full-stack-engineer', 'web-developer'],
    experienceLevel: 'mid',
    searchKeywords: ['full stack', 'full-stack developer', 'web development'],
    popularityScore: 91,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'devops-professional',
    name: 'DevOps Professional',
    description: 'Professional two-column for DevOps engineers',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['devops', 'infrastructure', 'cloud', 'sre'],
    targetRoles: ['devops-engineer', 'sre', 'platform-engineer', 'cloud-engineer'],
    experienceLevel: 'mid',
    searchKeywords: ['devops', 'sre', 'infrastructure', 'cloud', 'kubernetes'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'tech-lead',
    name: 'Tech Lead',
    description: 'Professional template for technical leaders',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['technology', 'leadership', 'engineering-management'],
    targetRoles: ['tech-lead', 'engineering-manager', 'team-lead'],
    experienceLevel: 'senior',
    searchKeywords: ['tech lead', 'technical lead', 'engineering manager', 'team lead'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'engineering-manager',
    name: 'Engineering Manager',
    description: 'Professional two-column for engineering managers',
    primaryCategory: 'tech-startup',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['engineering-management', 'leadership', 'technology'],
    targetRoles: ['engineering-manager', 'director-engineering', 'vp-engineering'],
    experienceLevel: 'senior',
    searchKeywords: ['engineering manager', 'em', 'director engineering', 'tech management'],
    popularityScore: 83,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },

  // ============================================================================
  // CREATIVE-DESIGN CATEGORY (15 templates)
  // ============================================================================
  {
    id: 'creative-modern',
    name: 'Creative Modern',
    description: 'Modern, visually striking template for creative professionals',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['design', 'creative', 'graphic-design', 'visual'],
    targetRoles: ['graphic-designer', 'visual-designer', 'creative-director'],
    experienceLevel: 'mid',
    searchKeywords: ['creative', 'design', 'modern design', 'visual'],
    popularityScore: 88,
    isFeatured: true,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'designer-portfolio',
    name: 'Designer Portfolio',
    description: 'Portfolio-focused template with project showcase',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['design', 'portfolio', 'creative', 'ux-ui'],
    targetRoles: ['designer', 'ux-designer', 'ui-designer', 'product-designer'],
    experienceLevel: 'mid',
    searchKeywords: ['designer', 'portfolio', 'ux', 'ui', 'product design'],
    popularityScore: 92,
    isFeatured: true,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'ux-designer',
    name: 'UX Designer',
    description: 'User-centric template for UX professionals',
    primaryCategory: 'creative-design',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['ux-design', 'user-experience', 'design', 'product'],
    targetRoles: ['ux-designer', 'ux-researcher', 'product-designer'],
    experienceLevel: 'mid',
    searchKeywords: ['ux', 'user experience', 'ux design', 'user research'],
    popularityScore: 90,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'graphic-designer',
    name: 'Graphic Designer',
    description: 'Visual template for graphic design professionals',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['graphic-design', 'visual-design', 'creative', 'branding'],
    targetRoles: ['graphic-designer', 'visual-designer', 'brand-designer'],
    experienceLevel: 'mid',
    searchKeywords: ['graphic design', 'visual design', 'branding', 'adobe'],
    popularityScore: 87,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'marketing-creative',
    name: 'Marketing Creative',
    description: 'Creative template for marketing professionals',
    primaryCategory: 'creative-design',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['marketing', 'creative', 'advertising', 'digital-marketing'],
    targetRoles: ['marketing-manager', 'creative-director', 'brand-manager'],
    experienceLevel: 'mid',
    searchKeywords: ['marketing', 'creative marketing', 'brand', 'advertising'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'brand-designer',
    name: 'Brand Designer',
    description: 'Template emphasizing brand and identity work',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['branding', 'design', 'creative', 'identity'],
    targetRoles: ['brand-designer', 'identity-designer', 'creative-director'],
    experienceLevel: 'mid',
    searchKeywords: ['brand design', 'branding', 'identity', 'creative'],
    popularityScore: 84,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'motion-graphics',
    name: 'Motion Graphics',
    description: 'Dynamic template for motion and animation designers',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['motion-graphics', 'animation', 'video', 'design'],
    targetRoles: ['motion-designer', 'animator', 'video-editor'],
    experienceLevel: 'mid',
    searchKeywords: ['motion graphics', 'animation', 'after effects', 'video'],
    popularityScore: 82,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'ui-designer',
    name: 'UI Designer',
    description: 'Interface-focused template for UI designers',
    primaryCategory: 'creative-design',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['ui-design', 'interface-design', 'design', 'product'],
    targetRoles: ['ui-designer', 'interface-designer', 'product-designer'],
    experienceLevel: 'mid',
    searchKeywords: ['ui design', 'interface', 'user interface', 'figma'],
    popularityScore: 89,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'content-creator',
    name: 'Content Creator',
    description: 'Versatile template for content creators and influencers',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['content-creation', 'social-media', 'creative', 'digital'],
    targetRoles: ['content-creator', 'social-media-manager', 'influencer'],
    experienceLevel: 'mid',
    searchKeywords: ['content creator', 'social media', 'creator', 'influencer'],
    popularityScore: 80,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'art-director',
    name: 'Art Director',
    description: 'Sophisticated template for art directors',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['art-direction', 'creative', 'design', 'advertising'],
    targetRoles: ['art-director', 'creative-director', 'senior-designer'],
    experienceLevel: 'senior',
    searchKeywords: ['art director', 'creative director', 'senior designer', 'leadership'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'photographer',
    name: 'Photographer',
    description: 'Visual template showcasing photography work',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['photography', 'visual', 'creative', 'media'],
    targetRoles: ['photographer', 'photo-editor', 'visual-artist'],
    experienceLevel: 'mid',
    searchKeywords: ['photographer', 'photography', 'visual artist', 'creative'],
    popularityScore: 79,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'web-designer',
    name: 'Web Designer',
    description: 'Modern template for web designers',
    primaryCategory: 'creative-design',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['web-design', 'design', 'frontend', 'ui-ux'],
    targetRoles: ['web-designer', 'frontend-designer', 'ui-designer'],
    experienceLevel: 'mid',
    searchKeywords: ['web design', 'web designer', 'frontend', 'html css'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'creative-director',
    name: 'Creative Director',
    description: 'Executive-level template for creative leaders',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['creative-direction', 'leadership', 'design', 'advertising'],
    targetRoles: ['creative-director', 'chief-creative-officer', 'design-director'],
    experienceLevel: 'executive',
    searchKeywords: ['creative director', 'cco', 'creative leadership', 'design executive'],
    popularityScore: 83,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'illustrator',
    name: 'Illustrator',
    description: 'Artistic template for illustrators and artists',
    primaryCategory: 'creative-design',
    designStyle: 'bold',
    pageLength: 'standard',
    atsCompatibility: 'visual-first',
    industryTags: ['illustration', 'art', 'creative', 'visual'],
    targetRoles: ['illustrator', 'artist', 'visual-artist'],
    experienceLevel: 'mid',
    searchKeywords: ['illustrator', 'illustration', 'artist', 'drawing'],
    popularityScore: 78,
    isFeatured: false,
    supportedFormats: ['pdf'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: false,
    templateConfig: {},
  },
  {
    id: 'product-designer',
    name: 'Product Designer',
    description: 'Comprehensive template for product designers',
    primaryCategory: 'creative-design',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['product-design', 'ux-ui', 'design', 'technology'],
    targetRoles: ['product-designer', 'ux-designer', 'design-lead'],
    experienceLevel: 'mid',
    searchKeywords: ['product design', 'product designer', 'ux ui', 'design thinking'],
    popularityScore: 91,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },

  // ============================================================================
  // ACADEMIC-RESEARCH CATEGORY (10 templates)
  // ============================================================================
  {
    id: 'academic-cv',
    name: 'Academic CV',
    description: 'Traditional CV template for academic positions',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['academic', 'research', 'education', 'university'],
    targetRoles: ['professor', 'researcher', 'postdoc', 'academic'],
    experienceLevel: 'senior',
    searchKeywords: ['academic cv', 'curriculum vitae', 'professor', 'research'],
    popularityScore: 89,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'research-scientist',
    name: 'Research Scientist',
    description: 'Detailed CV for research scientists',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['research', 'science', 'academic', 'phd'],
    targetRoles: ['research-scientist', 'scientist', 'researcher', 'principal-investigator'],
    experienceLevel: 'senior',
    searchKeywords: ['research scientist', 'phd', 'researcher', 'publications'],
    popularityScore: 87,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'faculty-position',
    name: 'Faculty Position',
    description: 'Comprehensive CV for faculty applications',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['academic', 'faculty', 'university', 'teaching'],
    targetRoles: ['assistant-professor', 'associate-professor', 'professor', 'lecturer'],
    experienceLevel: 'senior',
    searchKeywords: ['faculty', 'professor', 'teaching', 'academic position'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'postdoc-researcher',
    name: 'Postdoc Researcher',
    description: 'CV template for postdoctoral researchers',
    primaryCategory: 'academic-research',
    designStyle: 'minimal',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['postdoc', 'research', 'academic', 'phd'],
    targetRoles: ['postdoc', 'postdoctoral-researcher', 'research-fellow'],
    experienceLevel: 'mid',
    searchKeywords: ['postdoc', 'postdoctoral', 'research fellow', 'phd'],
    popularityScore: 84,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'phd-candidate',
    name: 'PhD Candidate',
    description: 'Academic CV for PhD candidates',
    primaryCategory: 'academic-research',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['phd', 'graduate-school', 'research', 'academic'],
    targetRoles: ['phd-student', 'doctoral-candidate', 'graduate-researcher'],
    experienceLevel: 'mid',
    searchKeywords: ['phd', 'doctoral', 'graduate student', 'dissertation'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'grant-application',
    name: 'Grant Application',
    description: 'CV optimized for grant and fellowship applications',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['research', 'grants', 'academic', 'fellowship'],
    targetRoles: ['researcher', 'principal-investigator', 'fellow'],
    experienceLevel: 'senior',
    searchKeywords: ['grant', 'fellowship', 'funding', 'research proposal'],
    popularityScore: 80,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'teaching-faculty',
    name: 'Teaching Faculty',
    description: 'CV emphasizing teaching experience and pedagogy',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['teaching', 'education', 'academic', 'faculty'],
    targetRoles: ['lecturer', 'instructor', 'teaching-professor'],
    experienceLevel: 'mid',
    searchKeywords: ['teaching', 'instructor', 'pedagogy', 'education'],
    popularityScore: 82,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'lab-researcher',
    name: 'Lab Researcher',
    description: 'Research-focused CV for laboratory scientists',
    primaryCategory: 'academic-research',
    designStyle: 'minimal',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['research', 'laboratory', 'science', 'biotech'],
    targetRoles: ['research-scientist', 'lab-manager', 'research-associate'],
    experienceLevel: 'mid',
    searchKeywords: ['lab research', 'laboratory', 'bench science', 'research methods'],
    popularityScore: 79,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'medical-researcher',
    name: 'Medical Researcher',
    description: 'CV for medical and clinical researchers',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['medical-research', 'clinical', 'healthcare', 'phd-md'],
    targetRoles: ['medical-researcher', 'clinical-investigator', 'physician-scientist'],
    experienceLevel: 'senior',
    searchKeywords: ['medical research', 'clinical research', 'physician scientist', 'md phd'],
    popularityScore: 81,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'publications-cv',
    name: 'Publications CV',
    description: 'CV highlighting publications and scholarly work',
    primaryCategory: 'academic-research',
    designStyle: 'traditional',
    pageLength: 'cv-length',
    atsCompatibility: 'ats-safe',
    industryTags: ['academic', 'research', 'publications', 'scholarly'],
    targetRoles: ['researcher', 'academic', 'author', 'scholar'],
    experienceLevel: 'senior',
    searchKeywords: ['publications', 'scholarly work', 'academic cv', 'author'],
    popularityScore: 83,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },

  // ============================================================================
  // EXECUTIVE-LEADERSHIP CATEGORY (10 templates)
  // ============================================================================
  {
    id: 'executive-modern',
    name: 'Executive Modern',
    description: 'Contemporary executive template for modern leaders',
    primaryCategory: 'executive-leadership',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['executive', 'c-suite', 'leadership', 'management'],
    targetRoles: ['ceo', 'president', 'c-level', 'executive-director'],
    experienceLevel: 'executive',
    searchKeywords: ['executive', 'ceo', 'c-suite', 'leadership'],
    popularityScore: 90,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'c-suite-elite',
    name: 'C-Suite Elite',
    description: 'Premium template for C-level executives',
    primaryCategory: 'executive-leadership',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['c-suite', 'executive', 'ceo', 'leadership'],
    targetRoles: ['ceo', 'cfo', 'coo', 'cto', 'cmo'],
    experienceLevel: 'executive',
    searchKeywords: ['c-suite', 'c-level', 'ceo', 'executive leadership'],
    popularityScore: 88,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'senior-director',
    name: 'Senior Director',
    description: 'Professional template for senior directors',
    primaryCategory: 'executive-leadership',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['director', 'senior-management', 'leadership'],
    targetRoles: ['senior-director', 'director', 'vp'],
    experienceLevel: 'executive',
    searchKeywords: ['senior director', 'director', 'vp', 'senior management'],
    popularityScore: 85,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'vp-executive',
    name: 'VP Executive',
    description: 'Distinguished template for vice presidents',
    primaryCategory: 'executive-leadership',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['vp', 'vice-president', 'executive', 'senior-leadership'],
    targetRoles: ['vp', 'vice-president', 'svp', 'evp'],
    experienceLevel: 'executive',
    searchKeywords: ['vice president', 'vp', 'svp', 'executive vp'],
    popularityScore: 86,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'board-member',
    name: 'Board Member',
    description: 'Executive CV for board positions and governance roles',
    primaryCategory: 'executive-leadership',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['board', 'governance', 'executive', 'leadership'],
    targetRoles: ['board-member', 'director', 'advisor', 'trustee'],
    experienceLevel: 'executive',
    searchKeywords: ['board member', 'board director', 'governance', 'advisory board'],
    popularityScore: 80,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'general-manager',
    name: 'General Manager',
    description: 'Leadership template for general managers',
    primaryCategory: 'executive-leadership',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['general-manager', 'management', 'operations', 'leadership'],
    targetRoles: ['general-manager', 'gm', 'operations-director'],
    experienceLevel: 'senior',
    searchKeywords: ['general manager', 'gm', 'operations', 'business leadership'],
    popularityScore: 82,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: false,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'strategic-leader',
    name: 'Strategic Leader',
    description: 'Template emphasizing strategic leadership and vision',
    primaryCategory: 'executive-leadership',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-friendly',
    industryTags: ['strategy', 'leadership', 'executive', 'transformation'],
    targetRoles: ['chief-strategy-officer', 'strategy-director', 'transformation-leader'],
    experienceLevel: 'executive',
    searchKeywords: ['strategic leader', 'strategy', 'transformation', 'vision'],
    popularityScore: 83,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'managing-director',
    name: 'Managing Director',
    description: 'Executive template for managing directors',
    primaryCategory: 'executive-leadership',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['managing-director', 'executive', 'leadership', 'senior-management'],
    targetRoles: ['managing-director', 'md', 'partner'],
    experienceLevel: 'executive',
    searchKeywords: ['managing director', 'md', 'partner', 'senior executive'],
    popularityScore: 84,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'operations-executive',
    name: 'Operations Executive',
    description: 'Template for COOs and operations leaders',
    primaryCategory: 'executive-leadership',
    designStyle: 'modern',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['operations', 'coo', 'executive', 'leadership'],
    targetRoles: ['coo', 'operations-director', 'vp-operations'],
    experienceLevel: 'executive',
    searchKeywords: ['coo', 'operations', 'chief operating officer', 'ops executive'],
    popularityScore: 81,
    isFeatured: false,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
  {
    id: 'chief-executive',
    name: 'Chief Executive',
    description: 'Premium template for CEOs and top executives',
    primaryCategory: 'executive-leadership',
    designStyle: 'traditional',
    pageLength: 'standard',
    atsCompatibility: 'ats-safe',
    industryTags: ['ceo', 'chief-executive', 'c-suite', 'leadership'],
    targetRoles: ['ceo', 'chief-executive-officer', 'president'],
    experienceLevel: 'executive',
    searchKeywords: ['ceo', 'chief executive', 'president', 'top executive'],
    popularityScore: 89,
    isFeatured: true,
    supportedFormats: ['pdf', 'docx'],
    usageCount: 0,
    isPremium: true,
    isDefault: false,
    isAtsSafe: true,
    templateConfig: {},
  },
];

/**
 * Seed all templates
 */
export async function seedTemplates() {
  console.log('🌱 Seeding 80 resume templates...');

  for (const template of templateSeeds) {
    await prisma.resumeTemplate.upsert({
      where: { id: template.id },
      update: template,
      create: template,
    });
  }

  console.log('✅ Successfully seeded 80 templates');
  console.log('   - ATS-Professional: 15 templates');
  console.log('   - Entry-Student: 15 templates');
  console.log('   - Tech-Startup: 15 templates');
  console.log('   - Creative-Design: 15 templates');
  console.log('   - Academic-Research: 10 templates');
  console.log('   - Executive-Leadership: 10 templates');
}

/**
 * Main seed function
 */
export default async function main() {
  try {
    await seedTemplates();
  } catch (error) {
    console.error('Error seeding templates:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run if called directly
if (require.main === module) {
  main()
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
