import { prisma } from '../src/utils/prisma';

// Color schemes (4 professional colors only)
const COLORS = {
  navy: { primary: '#1e3a8a', secondary: '#3b82f6', text: '#1e293b', background: '#ffffff' },
  emerald: { primary: '#047857', secondary: '#10b981', text: '#1e293b', background: '#ffffff' },
  slate: { primary: '#475569', secondary: '#64748b', text: '#1e293b', background: '#ffffff' },
  burgundy: { primary: '#881337', secondary: '#be123c', text: '#1e293b', background: '#ffffff' },
};

interface TemplateConfig {
  name: string;
  description: string;
  category: string;
  layout: string;
  designStyle: string;
  components: {
    header: string;
    experience: string;
    education: string;
    skills: string;
  };
  typography: {
    headingFont: string;
    bodyFont: string;
    size: string;
  };
  spacing: string;
  colorScheme: typeof COLORS.navy;
  atsCompatibility: number;
  photoSupport: boolean;
}

// Define 60 unique template designs
const TEMPLATE_DESIGNS: Omit<TemplateConfig, 'colorScheme'>[] = [
  // TRADITIONAL/FORMAL (10 templates)
  {
    name: 'Classic Professional',
    description: 'Traditional resume with serif fonts and formal structure. Perfect for corporate roles.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'traditional',
    components: { header: 'professional-formal', experience: 'bullet-point', education: 'traditional', skills: 'compact-list' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 98,
    photoSupport: false,
  },
  {
    name: 'Executive Summary',
    description: 'Premium executive resume with sophisticated typography and elegant spacing.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'executive',
    components: { header: 'executive-signature', experience: 'achievement-boxes', education: 'minimal', skills: 'categorized' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 95,
    photoSupport: true,
  },
  {
    name: 'Academic Formal',
    description: 'Research-focused template with emphasis on publications and education.',
    category: 'academic-research',
    layout: 'single-column',
    designStyle: 'academic',
    components: { header: 'academic-header', experience: 'detailed-description', education: 'detailed', skills: 'categorized' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 97,
    photoSupport: false,
  },
  {
    name: 'Corporate Standard',
    description: 'Standard corporate format with clear sections and professional appearance.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'corporate',
    components: { header: 'minimal', experience: 'compact-list', education: 'traditional', skills: 'table-grid' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 99,
    photoSupport: false,
  },
  {
    name: 'Banking Professional',
    description: 'Conservative design suitable for finance and banking positions.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'conservative',
    components: { header: 'professional-formal', experience: 'achievement-focused', education: 'traditional', skills: 'simple-list' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 98,
    photoSupport: false,
  },
  {
    name: 'Legal Professional',
    description: 'Formal template designed for legal professionals with emphasis on experience.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'formal',
    components: { header: 'traditional-centered', experience: 'detailed-description', education: 'detailed', skills: 'compact-list' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 97,
    photoSupport: false,
  },
  {
    name: 'Government Standard',
    description: 'ATS-optimized template meeting government application requirements.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'standard',
    components: { header: 'simple-header', experience: 'bullet-point', education: 'traditional', skills: 'simple-list' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 100,
    photoSupport: false,
  },
  {
    name: 'Medical Professional',
    description: 'Clean, professional template for healthcare positions.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'clinical',
    components: { header: 'professional-formal', experience: 'detailed-description', education: 'detailed', skills: 'categorized' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 96,
    photoSupport: true,
  },
  {
    name: 'Senior Executive',
    description: 'Premium template for C-level executives with executive summary section.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'premium',
    components: { header: 'executive-signature', experience: 'leadership-focused', education: 'minimal', skills: 'leadership-skills' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 94,
    photoSupport: true,
  },
  {
    name: 'Traditional Scholar',
    description: 'Academic template with focus on research and publications.',
    category: 'academic-research',
    layout: 'single-column',
    designStyle: 'scholarly',
    components: { header: 'academic-header', experience: 'research-focused', education: 'detailed', skills: 'technical-skills' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 96,
    photoSupport: false,
  },

  // MODERN/MINIMAL (10 templates)
  {
    name: 'Modern Minimal',
    description: 'Clean, minimalist design with lots of whitespace and modern typography.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'minimal',
    components: { header: 'minimal', experience: 'clean-list', education: 'minimal', skills: 'simple-tags' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 92,
    photoSupport: true,
  },
  {
    name: 'Clean Professional',
    description: 'Modern professional look with clear hierarchy and breathing room.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'clean',
    components: { header: 'modern-header', experience: 'compact-list', education: 'minimal', skills: 'chip' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 94,
    photoSupport: true,
  },
  {
    name: 'Geometric Modern',
    description: 'Contemporary design with geometric shapes and bold section headers.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'geometric',
    components: { header: 'geometric-header', experience: 'modern-cards', education: 'minimal', skills: 'progress-circles' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 88,
    photoSupport: true,
  },
  {
    name: 'Swiss Style',
    description: 'Inspired by Swiss design principles with grid-based layout.',
    category: 'creative-design',
    layout: 'single-column',
    designStyle: 'swiss',
    components: { header: 'grid-header', experience: 'grid-layout', education: 'grid-style', skills: 'grid-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 85,
    photoSupport: false,
  },
  {
    name: 'Scandinavian Clean',
    description: 'Nordic-inspired minimalism with functional beauty.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'scandinavian',
    components: { header: 'clean-simple', experience: 'minimal-list', education: 'minimal', skills: 'simple-bars' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 90,
    photoSupport: true,
  },
  {
    name: 'Minimalist Pro',
    description: 'Professional minimalism with strategic use of accent colors.',
    category: 'ats-professional',
    layout: 'single-column',
    designStyle: 'minimalist',
    components: { header: 'minimal-accent', experience: 'clean-bullets', education: 'minimal', skills: 'clean-list' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 93,
    photoSupport: true,
  },
  {
    name: 'Contemporary',
    description: 'Modern template with contemporary styling and clean lines.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'contemporary',
    components: { header: 'modern-split', experience: 'timeline-modern', education: 'minimal', skills: 'skill-tags' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 89,
    photoSupport: true,
  },
  {
    name: 'Urban Professional',
    description: 'Sleek urban design with modern aesthetics.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'urban',
    components: { header: 'bold-modern', experience: 'modern-list', education: 'minimal', skills: 'icon-list' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 87,
    photoSupport: true,
  },
  {
    name: 'Tech Minimalist',
    description: 'Developer-friendly minimal design with technical aesthetic.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'tech-minimal',
    components: { header: 'tech-header', experience: 'code-style', education: 'minimal', skills: 'technical-list' },
    typography: { headingFont: 'mono', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 91,
    photoSupport: false,
  },
  {
    name: 'Airy Space',
    description: 'Maximum whitespace with breathing room for easy reading.',
    category: 'creative-design',
    layout: 'single-column',
    designStyle: 'airy',
    components: { header: 'spacious-header', experience: 'spaced-list', education: 'minimal', skills: 'spaced-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 86,
    photoSupport: true,
  },

  // CREATIVE/BOLD (10 templates)
  {
    name: 'Creative Showcase',
    description: 'Bold, creative design for designers and creative professionals.',
    category: 'creative-design',
    layout: 'single-column',
    designStyle: 'creative',
    components: { header: 'gradient-background', experience: 'project-highlight', education: 'creative', skills: 'tag-cloud' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'large' },
    spacing: 'balanced',
    atsCompatibility: 75,
    photoSupport: true,
  },
  {
    name: 'Bold Impact',
    description: 'High-impact design with large typography and bold sections.',
    category: 'creative-design',
    layout: 'single-column',
    designStyle: 'bold',
    components: { header: 'large-headline', experience: 'bold-sections', education: 'creative', skills: 'visual-skills' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'extra-large' },
    spacing: 'spacious',
    atsCompatibility: 72,
    photoSupport: true,
  },
  {
    name: 'Artistic Portfolio',
    description: 'Portfolio-style resume for artists and designers.',
    category: 'creative-design',
    layout: 'two-column-right',
    designStyle: 'artistic',
    components: { header: 'photo-prominent', experience: 'portfolio-grid', education: 'sidebar', skills: 'visual-bars' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 70,
    photoSupport: true,
  },
  {
    name: 'Designer Pro',
    description: 'Professional designer template with creative flair.',
    category: 'creative-design',
    layout: 'two-column-left',
    designStyle: 'designer',
    components: { header: 'creative-header', experience: 'project-cards', education: 'sidebar', skills: 'icon-grid' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 78,
    photoSupport: true,
  },
  {
    name: 'Vibrant Creative',
    description: 'Energetic design with bold colors and dynamic layout.',
    category: 'creative-design',
    layout: 'single-column',
    designStyle: 'vibrant',
    components: { header: 'colorful-header', experience: 'dynamic-sections', education: 'creative', skills: 'colorful-tags' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'large' },
    spacing: 'balanced',
    atsCompatibility: 68,
    photoSupport: true,
  },
  {
    name: 'Magazine Style',
    description: 'Editorial magazine-inspired layout.',
    category: 'creative-design',
    layout: 'two-column-right',
    designStyle: 'magazine',
    components: { header: 'magazine-header', experience: 'article-style', education: 'sidebar', skills: 'sidebar-list' },
    typography: { headingFont: 'display', bodyFont: 'serif', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 74,
    photoSupport: true,
  },
  {
    name: 'Asymmetric Creative',
    description: 'Unique asymmetric layout for standing out.',
    category: 'creative-design',
    layout: 'two-column-left',
    designStyle: 'asymmetric',
    components: { header: 'asymmetric-header', experience: 'staggered-sections', education: 'offset', skills: 'floating-skills' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'medium' },
    spacing: 'creative',
    atsCompatibility: 65,
    photoSupport: true,
  },
  {
    name: 'Infographic Style',
    description: 'Visual infographic approach to resume design.',
    category: 'creative-design',
    layout: 'two-column-right',
    designStyle: 'infographic',
    components: { header: 'visual-header', experience: 'timeline-visual', education: 'visual', skills: 'chart-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'compact',
    atsCompatibility: 60,
    photoSupport: true,
  },
  {
    name: 'Colorblock Design',
    description: 'Bold color blocks defining sections.',
    category: 'creative-design',
    layout: 'single-column',
    designStyle: 'colorblock',
    components: { header: 'block-header', experience: 'block-sections', education: 'block-style', skills: 'block-skills' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'large' },
    spacing: 'balanced',
    atsCompatibility: 70,
    photoSupport: true,
  },
  {
    name: 'Modern Artist',
    description: 'Contemporary artistic template for creative roles.',
    category: 'creative-design',
    layout: 'two-column-left',
    designStyle: 'modern-art',
    components: { header: 'artistic-header', experience: 'showcase-style', education: 'sidebar', skills: 'artistic-skills' },
    typography: { headingFont: 'display', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 72,
    photoSupport: true,
  },

  // TECHNICAL/DEVELOPER (10 templates)
  {
    name: 'Developer Pro',
    description: 'Clean developer-focused template with technical aesthetic.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'developer',
    components: { header: 'tech-header', experience: 'code-blocks', education: 'technical', skills: 'tech-stack' },
    typography: { headingFont: 'mono', bodyFont: 'mono', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 90,
    photoSupport: false,
  },
  {
    name: 'Code Style',
    description: 'IDE-inspired design with syntax highlighting aesthetics.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'code',
    components: { header: 'terminal-header', experience: 'code-style', education: 'technical', skills: 'programming-skills' },
    typography: { headingFont: 'mono', bodyFont: 'mono', size: 'medium' },
    spacing: 'compact',
    atsCompatibility: 88,
    photoSupport: false,
  },
  {
    name: 'GitHub Style',
    description: 'Inspired by GitHub profile with contribution graph aesthetic.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'github',
    components: { header: 'github-header', experience: 'repo-style', education: 'minimal', skills: 'tech-badges' },
    typography: { headingFont: 'mono', bodyFont: 'sans', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 85,
    photoSupport: true,
  },
  {
    name: 'Terminal Theme',
    description: 'Command-line terminal inspired design.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'terminal',
    components: { header: 'cli-header', experience: 'terminal-output', education: 'technical', skills: 'command-list' },
    typography: { headingFont: 'mono', bodyFont: 'mono', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 82,
    photoSupport: false,
  },
  {
    name: 'Tech Stack Pro',
    description: 'Showcase technical skills and stack prominently.',
    category: 'tech-startup',
    layout: 'two-column-left',
    designStyle: 'tech-stack',
    components: { header: 'tech-banner', experience: 'project-based', education: 'sidebar', skills: 'stack-visualization' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 87,
    photoSupport: false,
  },
  {
    name: 'Full Stack Developer',
    description: 'Comprehensive template for full-stack developers.',
    category: 'tech-startup',
    layout: 'two-column-right',
    designStyle: 'fullstack',
    components: { header: 'developer-header', experience: 'project-showcase', education: 'sidebar', skills: 'fullstack-skills' },
    typography: { headingFont: 'sans', bodyFont: 'mono', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 89,
    photoSupport: true,
  },
  {
    name: 'DevOps Engineer',
    description: 'Template optimized for DevOps and infrastructure roles.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'devops',
    components: { header: 'tech-header', experience: 'infrastructure-focus', education: 'technical', skills: 'devops-tools' },
    typography: { headingFont: 'mono', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 91,
    photoSupport: false,
  },
  {
    name: 'Data Scientist',
    description: 'Analytics-focused template with data visualization emphasis.',
    category: 'tech-startup',
    layout: 'two-column-right',
    designStyle: 'data-science',
    components: { header: 'data-header', experience: 'research-projects', education: 'academic', skills: 'data-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 86,
    photoSupport: true,
  },
  {
    name: 'Systems Architect',
    description: 'Enterprise architecture and systems design focused.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'architect',
    components: { header: 'professional-tech', experience: 'architecture-focus', education: 'technical', skills: 'systems-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 92,
    photoSupport: false,
  },
  {
    name: 'ML Engineer',
    description: 'Machine learning and AI engineering template.',
    category: 'tech-startup',
    layout: 'single-column',
    designStyle: 'ml-engineer',
    components: { header: 'tech-header', experience: 'ml-projects', education: 'academic', skills: 'ml-frameworks' },
    typography: { headingFont: 'sans', bodyFont: 'mono', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 88,
    photoSupport: false,
  },

  // EXECUTIVE/PREMIUM (10 templates)
  {
    name: 'Executive Elite',
    description: 'Luxury executive template with premium finishes.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'luxury',
    components: { header: 'executive-gold', experience: 'leadership-achievements', education: 'executive-education', skills: 'leadership-competencies' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 90,
    photoSupport: true,
  },
  {
    name: 'C-Suite Professional',
    description: 'Designed specifically for C-level executives.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'c-suite',
    components: { header: 'executive-banner', experience: 'board-level', education: 'minimal', skills: 'strategic-skills' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 92,
    photoSupport: true,
  },
  {
    name: 'Board Director',
    description: 'Premium template for board members and directors.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'director',
    components: { header: 'director-header', experience: 'governance-focus', education: 'executive-education', skills: 'governance-skills' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 91,
    photoSupport: true,
  },
  {
    name: 'VP Leadership',
    description: 'Vice President level template emphasizing leadership.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'vp-level',
    components: { header: 'vp-header', experience: 'leadership-impact', education: 'executive-education', skills: 'strategic-leadership' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 93,
    photoSupport: true,
  },
  {
    name: 'Senior Leadership',
    description: 'Refined template for senior management positions.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'senior-mgmt',
    components: { header: 'senior-header', experience: 'management-achievements', education: 'executive-education', skills: 'management-skills' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 94,
    photoSupport: true,
  },
  {
    name: 'Global Executive',
    description: 'International executive with multilingual support.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'global',
    components: { header: 'global-header', experience: 'international-experience', education: 'global-education', skills: 'global-competencies' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 89,
    photoSupport: true,
  },
  {
    name: 'Strategic Leader',
    description: 'Emphasis on strategic planning and vision.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'strategic',
    components: { header: 'strategic-header', experience: 'strategic-initiatives', education: 'executive-education', skills: 'strategic-thinking' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'large' },
    spacing: 'spacious',
    atsCompatibility: 91,
    photoSupport: true,
  },
  {
    name: 'Transformational Leader',
    description: 'Showcase transformation and change management.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'transformation',
    components: { header: 'transformation-header', experience: 'transformation-projects', education: 'executive-education', skills: 'change-leadership' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 90,
    photoSupport: true,
  },
  {
    name: 'Finance Executive',
    description: 'Premium template for CFOs and finance leaders.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'finance-exec',
    components: { header: 'finance-header', experience: 'financial-achievements', education: 'executive-education', skills: 'financial-acumen' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 93,
    photoSupport: true,
  },
  {
    name: 'Operations Executive',
    description: 'COO-focused template emphasizing operational excellence.',
    category: 'executive-leadership',
    layout: 'single-column',
    designStyle: 'operations-exec',
    components: { header: 'ops-header', experience: 'operational-achievements', education: 'executive-education', skills: 'operational-excellence' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 92,
    photoSupport: true,
  },

  // ENTRY/STUDENT (10 templates)
  {
    name: 'Fresh Graduate',
    description: 'Optimized for recent graduates with emphasis on education.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'graduate',
    components: { header: 'student-header', experience: 'internship-focus', education: 'detailed-education', skills: 'learning-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 88,
    photoSupport: true,
  },
  {
    name: 'Student Professional',
    description: 'Clean template for students entering the workforce.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'student',
    components: { header: 'modern-student', experience: 'coursework-projects', education: 'academic-focus', skills: 'technical-coursework' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 90,
    photoSupport: true,
  },
  {
    name: 'Internship Seeker',
    description: 'Designed for students seeking internships.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'internship',
    components: { header: 'friendly-header', experience: 'relevant-coursework', education: 'education-first', skills: 'soft-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'spacious',
    atsCompatibility: 91,
    photoSupport: true,
  },
  {
    name: 'Campus Recruit',
    description: 'Perfect for campus recruitment and career fairs.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'campus',
    components: { header: 'campus-header', experience: 'extracurricular', education: 'gpa-focus', skills: 'campus-activities' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 89,
    photoSupport: true,
  },
  {
    name: 'Entry Level Pro',
    description: 'Professional entry-level template for first job.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'entry-professional',
    components: { header: 'professional-entry', experience: 'achievement-focus', education: 'education-highlight', skills: 'growing-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 92,
    photoSupport: false,
  },
  {
    name: 'Career Starter',
    description: 'Energetic design for career beginners.',
    category: 'entry-student',
    layout: 'two-column-left',
    designStyle: 'starter',
    components: { header: 'energetic-header', experience: 'potential-focus', education: 'sidebar-education', skills: 'eager-learner' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 87,
    photoSupport: true,
  },
  {
    name: 'Academic Excellence',
    description: 'Highlight academic achievements and honors.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'academic-student',
    components: { header: 'academic-header', experience: 'academic-projects', education: 'honors-focus', skills: 'academic-skills' },
    typography: { headingFont: 'serif', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 90,
    photoSupport: false,
  },
  {
    name: 'Scholarship Winner',
    description: 'Emphasize scholarships and academic recognition.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'scholarship',
    components: { header: 'achievement-header', experience: 'leadership-activities', education: 'scholarship-focus', skills: 'leadership-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 88,
    photoSupport: true,
  },
  {
    name: 'Co-op Student',
    description: 'For students with co-op or work-study experience.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'coop',
    components: { header: 'work-study-header', experience: 'coop-experience', education: 'education-highlight', skills: 'practical-skills' },
    typography: { headingFont: 'sans', bodyFont: 'sans', size: 'medium' },
    spacing: 'balanced',
    atsCompatibility: 91,
    photoSupport: false,
  },
  {
    name: 'Graduate School',
    description: 'Designed for graduate school applications.',
    category: 'entry-student',
    layout: 'single-column',
    designStyle: 'grad-school',
    components: { header: 'academic-header', experience: 'research-experience', education: 'research-focus', skills: 'research-skills' },
    typography: { headingFont: 'serif', bodyFont: 'serif', size: 'small' },
    spacing: 'compact',
    atsCompatibility: 93,
    photoSupport: false,
  },
];

async function generateTemplates() {
  console.log('🎨 Generating 60 distinct templates...\n');

  const templates: any[] = [];

  // Generate templates with color variations
  for (const design of TEMPLATE_DESIGNS) {
    // For each design, create with one color (not all 4)
    const colorName = design.category.includes('executive') ? 'navy' :
                     design.category.includes('creative') ? 'burgundy' :
                     design.category.includes('tech') ? 'slate' : 'emerald';

    const color = COLORS[colorName as keyof typeof COLORS];

    templates.push({
      name: design.name,
      description: design.description,
      primaryCategory: design.category,
      designStyle: design.designStyle,
      pageLength: 'single',
      atsCompatibility: design.atsCompatibility >= 90 ? 'ATS-Safe' :
                       design.atsCompatibility >= 80 ? 'ATS-Friendly' : 'Visual-First',
      industryTags: [],
      targetRoles: [],
      experienceLevel: design.category === 'entry-student' ? 'Entry' :
                      design.category === 'executive-leadership' ? 'Executive' : 'Mid',
      searchKeywords: [design.designStyle, design.category, design.layout],
      popularityScore: Math.floor(Math.random() * 50) + 50,
      isFeatured: Math.random() > 0.8,
      supportedFormats: ['pdf', 'docx'],
      usageCount: 0,
      isPremium: design.category === 'executive-leadership' || design.category === 'creative-design',
      isDefault: design.name === 'Classic Professional',
      isAtsSafe: design.atsCompatibility >= 90,
      photoSupport: design.photoSupport,
      templateConfig: {
        layout: design.layout,
        components: design.components,
        typography: design.typography,
        spacing: design.spacing,
        colorScheme: { ...color, name: colorName },
        atsCompatibility: design.atsCompatibility,
        photoSupport: design.photoSupport,
        category: design.category,
        primaryCategory: design.category,
        designStyle: design.designStyle,
      },
    });
  }

  console.log(`📝 Created ${templates.length} template configurations`);
  console.log(`   - Traditional/Formal: 10`);
  console.log(`   - Modern/Minimal: 10`);
  console.log(`   - Creative/Bold: 10`);
  console.log(`   - Technical/Developer: 10`);
  console.log(`   - Executive/Premium: 10`);
  console.log(`   - Entry/Student: 10\n`);

  // Insert into database
  console.log('💾 Inserting templates into database...');
  await prisma.resumeTemplate.createMany({
    data: templates,
  });

  console.log('✅ Templates inserted successfully!\n');

  // Verify
  const count = await prisma.resumeTemplate.count();
  console.log(`✅ Total templates in database: ${count}`);

  await prisma.$disconnect();
}

generateTemplates().catch(console.error);
